### ISSUE TITLE
Feature request: Handle Profile setting on Cleanflight

### ISSUE THREAD

**Issue by Spirre** [ShikOfTheRa/scarab-osd#10]
I've not find this feature so please correct me if I'm wrong. It would be nice to to able to see and also change profile when you are using cleanflight.

**Comment by ShikOfTheRa** [comment]
I have added to the wish list, but I think its unlikely to be added due to lack of memory.unfortunately other features will be worked on first

**Comment by ShikOfTheRa** [comment]
Feedback from forum: This is not possible. Sorry

**Comment by ShikOfTheRa** [comment]
This is now added - profile / pid controller. Also looptime if supported
