### ISSUE TITLE
Java 8 causes exception during GUI startup

### ISSUE THREAD

**Issue by JoeB99** [ShikOfTheRa/scarab-osd#100]
Win7, x64

1.4.1
When starting the GUI, a java 'animation' exception is thrown in the console window.

1.2
An "unspecified error" popup appears.

Both versions:

Uninstalling Java 8, and installing Java 7 update 80 (downloaded from Java.com) fixes the issue.

**Comment by ShikOfTheRa** [comment]
I am using 1.8 !
The messages above are also what you would see if running a 32bit gui on 64 bit java or vice versa.

**Comment by JoeB99** [comment]
1.8 ? The latest version in the downloads section is R1.4.1.
Is there a new release?

**Comment by ShikOfTheRa** [comment]
Sorry for confusion - Java 1.8 
MWOSD R1.5 will be out soon. Just waiting for completion of testing for various platforms.
Will be very close to this beta test release...
https://github.com/ShikOfTheRa/scarab-osd/releases/tag/v1.4.2.11
