### ISSUE TITLE
Can't change PIDs

### ISSUE THREAD

**Issue by dustin** [ShikOfTheRa/scarab-osd#105]
I'm getting this behavior in a recent build:

https://www.youtube.com/watch?v=1Fi-J5m9zZM

(latest baseflight / current master MWOSD)

**Comment by lichtl** [comment]
Have you already tried the latest code? There was an issue #98 which looks equal which have been solved with commit 9da63b36ca4ac24d9179dc67d668a745606cf73e

**Comment by dustin** [comment]
I filed that bug immediately after flashing master.  I can double check
when I get home, but it's hard to verify the exact commit without putting
'git describe' output on the screen.

**Comment by ShikOfTheRa** [comment]
There was an issue. Saw exactly problem you described but I'm not seeing this in the latest
