### ISSUE TITLE
Enable GPS Time in config.h compile error

### ISSUE THREAD

**Issue by Gregmaan** [ShikOfTheRa/scarab-osd#107]
When I enable the GPSTime feature in config.h I can´t compile anymore.
Tested with 1.4.2.5 and 1.5.0.0 with Arduino 1.6.5

**Comment by ShikOfTheRa** [comment]
What message do you get. 1.5.0.0 compiles Ok here. am running 1.0.6 though

**Comment by Gregmaan** [comment]
Ok, with the old 1.06 its OK.
