### ISSUE TITLE
GUI stuck on "Waiting OSD" v1.5

### ISSUE THREAD

**Issue by ronnke** [ShikOfTheRa/scarab-osd#113]
FC: Paris v5r3 (Multiwii 2.4)
OS: Windows 10 (64bit) w/64bit Java

After flashing from 1.4.1 to 1.5, when in the GUI and selecting the comm port to connect to the OSD, the message "Waiting OSD" will flash indefinitely with no connection established. 

Flashing back to 1.4.1 and everything works as expected.

**Comment by ShikOfTheRa** [comment]
Actually I am using that board too!

Occasionally  I get some this sort of comment – although I haven’t experienced myself and I have programmed many many times. So really I have no idea why


Make sure use a GUI from same version that is on the board. Easy to mix up sometimes.

First try…
When connected click default a couple of times, then restart. Also power cycle or use the button on the OSD programmer.

Second try:
Upload EEPROM_CLEAR skletch and running that before uploading MWOSD. Thee is also a facility for this in the beginning of config.h of latest version which might be more convenient..
