### ISSUE TITLE
Mission mode activated when using telemetry switch on Cleanflight

### ISSUE THREAD

**Issue by Netsplits** [ShikOfTheRa/scarab-osd#114]
I've setup on Cleanflight 1.9 a switch to enable telemetry, even in disarmed mode, and when I set the switch on, the OSD unexpectedly enters MISSION mode. I've something wrong on my configuration?

**Comment by ShikOfTheRa** [comment]
Just looked- it appears cleanflight are using same status bit for telemetry as multiwii uses for GPS waypoints. I'll have to make amendment to accommodate this.

**Comment by ShikOfTheRa** [comment]
Have made some changes - please test to see if it works.
GUI is same - just need to upload new sketch to OSD
 
https://github.com/ShikOfTheRa/scarab-osd/archive/master.zip

**Comment by Netsplits** [comment]
Sorry for the late feedback, but it works perfectly now. Thanks.

**Comment by Netsplits** [comment]
Don't know if it's because I've just upgraded to Cleanflight 1.10 version, but mission appears again, not sure what did activate it, I suppose IDs have changed again on Cleanflight code...
