### ISSUE TITLE
Cannot make "Fly Time" visible in Layout Editor

### ISSUE THREAD

**Issue by joshuabardwell** [ShikOfTheRa/scarab-osd#118]
When I enable "Fly Time" in the layout editor, the field does not appear on the layout. Other values seem to depend on switches as to whether they appear or not, but I can't find a switch that corresponds to Fly Time.

**Comment by ShikOfTheRa** [comment]
On GUI it is labelled "Display Timer"
In Layout editor there are two - "FlyTime" and "Ontime". Its from legacy code which need to be consolidated to a single position at some point.
Both need to be enabled and likely in same position. 

In code, both clocks are running, but only one is ever displayed. When armed the flytime is displayed. Else its on time

**Comment by joshuabardwell** [comment]
>When armed the flytime is displayed. Else its on time

Ahh. Thanks. That was the piece I was missing.
