### ISSUE TITLE
Nothing but voltage and armed status

### ISSUE THREAD

**Issue by lowki** [ShikOfTheRa/scarab-osd#122]
Running latest version on a micro minimosd, connected to a naze32 rev5 fc running latest cleanflight.

The only datas displayed on screen are the battery voltage (read from fc), and the armed status, no horizon, no amp, no flight mode.
I've tried all fonts avaiable, but nothing happens.

**Comment by ShikOfTheRa** [comment]
Maybe you have the minimal screen layout enabled?

**Comment by lowki** [comment]
I don't think so, when tx/rx pins are disconnected, current, flight mode, armed status and voltage are displayed, obviously without datas.

**Comment by lowki** [comment]
Ok, found it, in cleanflight, the osd switch was activated.
