### ISSUE TITLE
Voltage showing zero on cleanflight

### ISSUE THREAD

**Issue by bk79** [ShikOfTheRa/scarab-osd#126]
@ShikOfTheRa I've tried compiling the latest revion with cleanflight and battery level from FC shows zero on cleanflight 1.11 I've correctly configured the config.h to be working with cleanflight decommenting cleanflight only

**Comment by ShikOfTheRa** [comment]
Is it only an issue with 1.11?

**Comment by bk79** [comment]
No idea i'm using this release  now never tried pm previous one

Il giorno 23:40 dom 11/ott/2015 ShikOfTheRa <notifications@github.com> ha
scritto:

**Comment by ShikOfTheRa** [comment]
Have you selected the correct board? 

If still same, try connecting to bat2 - some boards have tave bat1/bat2 reversed

**Comment by bk79** [comment]
Nope I'm using FCC values

Il giorno 10:10 lun 12/ott/2015 ShikOfTheRa <notifications@github.com> ha
scritto:

**Comment by ShikOfTheRa** [comment]
Ha - I didn't read your initial comment fully
Just tested on simulator and it work ok here. This means OK in Multiwii, baseflight and older cleanflight.
I don't know if 1.11 has changed. I'll be upgrading at some point but not sure when can test.

**Comment by ShikOfTheRa** [comment]
Hi is this still an issue?

**Comment by bk79** [comment]
I'll tell you in 20 days I burned my miniosd so waiting for a new one to
arrive from china

Il giorno 12:51 lun 19/ott/2015 ShikOfTheRa <notifications@github.com> ha
scritto:

**Comment by dustin** [comment]
@bk79 have you confirmed your flight controller was receiving the correct values itself?
