### ISSUE TITLE
wrong rxtxSerial.dll in MWOSD

### ISSUE THREAD

**Issue by bk79** [ShikOfTheRa/scarab-osd#127]
on win64 rxtxSerial.dll is wrong just copying it over from win32 version fixed it

**Comment by ShikOfTheRa** [comment]
mm. I am using win64 with 64 bit and seems to be running OK with no error messages.
Are you running 32 or 64 bit java? the version is more to do with that than windows version

**Comment by bk79** [comment]
window64 bit no idea of what I've installed but 32 bit doesn't run and 64bit runs with that trick

**Comment by ShikOfTheRa** [comment]
Closing as it sounds resolved
