### ISSUE TITLE
Beta 1.5.1 does not include Mac GUI

### ISSUE THREAD

**Issue by JohnOCFII** [ShikOfTheRa/scarab-osd#131]
The Beta 1.5.1 zip doesn't include the Mac GUI app.  I downloaded the version from the released 1.5, and that worked fine.

**Comment by ShikOfTheRa** [comment]
Yes - unfortunately I don't have a mac and the version produced by the compiler doesn't work so the beta tests don't come with it - sorry...

If you have a mac, you can install processing and run the source code - or create your own executable. Its very easy - very similar to arduino look/feel

**Comment by JohnOCFII** [comment]
> Yes - unfortunately I don't have a mac and the version produced by the compiler doesn't work so the beta tests don't come with it - sorry...

No problem.  I'll take a look at building my own executable.    Thanks for the fast reply.

**Comment by andyshinn** [comment]
I can't find any documentation running it with processing. Can you point us to the sketch folder in the source?

**Comment by nathantsoi** [comment]
open processing and open:

![screen shot 2015-11-23 at 10 09 54 am](https://cloud.githubusercontent.com/assets/399770/11345228/6fa535fe-91ca-11e5-9e28-54944db049c4.png)
