### ISSUE TITLE
Traditional aeronautical units of measure?

### ISSUE THREAD

**Issue by jaffadog** [ShikOfTheRa/scarab-osd#135]
Hi - I'd also be interested in seeing aueronautical units as an option, in addition to metric and imperial.  i.e. speed in knots, distance in nautical miles, altitude in feet.

**Comment by ShikOfTheRa** [comment]
I have added this too the wish list.
It is low priority - so not sure when it will be completed

**Comment by ShikOfTheRa** [comment]
Closing as on teh roadmap list
