### ISSUE TITLE
Is anyone flying blackbox + scarab-osd?

### ISSUE THREAD

**Issue by nathantsoi** [ShikOfTheRa/scarab-osd#136]
Currently it seems this is not possible since the serial port switches from MSP to blackbox logging when armed.

It would be awesome if the OSD could auto-switch input from MSP to blackbox when the FC is armed.

Would anyone else use this feature?

**Comment by ShikOfTheRa** [comment]
Sorry - no plans to support this config.
Can you use other serial for OSD instead

**Comment by timotto** [comment]
It works on two different serial ports with cleanflight 1.10, blackbox at 250000bps, osd at 115200bps

**Comment by dustin** [comment]
This is a configuration issue on your flight controller, not an MWOSD bug.  Trying to detect when protocol and speed change so you can pick out relevant bits from an obscure protocol at a different baud rate to pick out a few bits of information for display would be quite a challenge.

Is there a standard blackbox protocol spec?  Perhaps you could construct a PR to sniff that protocol and operate on relevant frames received.
