### ISSUE TITLE
GPS Altitude not working  MW_OSD R1.5 

### ISSUE THREAD

**Issue by falkindustries** [ShikOfTheRa/scarab-osd#143]
I´m using MW_OSD R1.5 with a MinimOSD on cleanflight (drones) and on baseflight (fixed wings).
On both I´m not able to display the GPS Altitude (not BARO Alt). Everything else works just fine (Speed, Direction, Sats...).
Is that a bug or am i missing something?
Thank you for help!!!

**Comment by ShikOfTheRa** [comment]
Not aware or have had anything reported. Seems to work for me too.
