### ISSUE TITLE
No voltage (0.0) on micro minimosd

### ISSUE THREAD

**Issue by otbe** [ShikOfTheRa/scarab-osd#146]
Hi,

Im using MWOSD R1.5 on my brand new micro minimosd with a CC3D on Cleanflight 1.10. Everything works (Flightmode, AHI, Armed/Disarmed) except for main/vid voltages. 

My 3S Lipo is connected directly to the micro minimosd. I have tried `#define WITESPYV1`, `#define WITESPYMICRO`, bat1/bat2 pad in every possible combination so far, but nothing helps. The main/vid voltages are blinking all the time with value 0.0.

Right before Cleanflight I tried OpenPilot on the CC3D with minOPOSD on the micro minimosd and there the main voltage works as expected. So its not a faulty chip.

Any kind of advices for me? :)

Thanks!

Edit: `Use FC main voltage` is not activated.

**Comment by ShikOfTheRa** [comment]
Have not had any issues reported here - the most common is that it is connected to wrong bat1/bat2 - but you appear to have tested.

Note support is via fpvlab forum . thanks.
