### ISSUE TITLE
# cells not pesistantly determined at POR

### ISSUE THREAD

**Issue by Hwurzburg** [ShikOfTheRa/scarab-osd#152]
autodetect of cells should be done once at POR and not calculated very loop for alarms and batt status icon....this allows both to work when bat falls below min cell voltage

**Comment by ShikOfTheRa** [comment]
Yes, agree. Have moved that bit into period where the welcome screen is displayed. Its strictly not strictly a run once, but will prevent falling into a lower cell count range during use.
