### ISSUE TITLE
Batt status icon allocation is non uniform due to incorrect use of map() call

### ISSUE THREAD

**Issue by Hwurzburg** [ShikOfTheRa/scarab-osd#154]
see my previous  pull request for proper useage of this call

**Comment by ShikOfTheRa** [comment]
OK have made some changes - not perfect due to rounding errors and trying to keep memory utilisation low. But its pretty close. let me know what think

Cant set the map constraint to 7 - it provided a bad icon at max voltage.

**Comment by Hwurzburg** [comment]
The input should be constrained to inmin and inmax...then the map call should be of the form map(var,inmin,inmax+1,outmin,outmax+1)

**Comment by Hwurzburg** [comment]
Look at my pull request code

**Comment by ShikOfTheRa** [comment]
Ah yep I got you. .... will revisit it.

**Comment by ShikOfTheRa** [comment]
OK - done - thanks for contribution !!
