### ISSUE TITLE
Cannot adjust "Amps adjust" through OSD menu in 1.5.2

### ISSUE THREAD

**Issue by flounderscore** [ShikOfTheRa/scarab-osd#164]
With the latest 1.5.2 version I can't adjust the "Amps adjust" through the OSD menu anymore. It always shows a value of "2" and can't be changed (instead of "150"). The current offset can be changed just fine.

**Comment by ShikOfTheRa** [comment]
Yes - confirmed. My error - missed some bits in the change. Have updated the repository - but there are other changes in there so will require a new GUI to be compiled.

**Comment by ShikOfTheRa** [comment]
Closing as will be available via 1.5.3 or 1.6 when released
