### ISSUE TITLE
Forced crosshair position is off center because of the new defaults

### ISSUE THREAD

**Issue by CrazyCoder** [ShikOfTheRa/scarab-osd#175]
It looks like https://github.com/ShikOfTheRa/scarab-osd/commit/07d03bec0c1260de5e23b923ee8cd51517057d37 has broken the forced crosshair display position.

You forgot to change the code inside https://github.com/ShikOfTheRa/scarab-osd/blob/master/MW_OSD/Screen.ino#L1794.

Should looks like this now:

```
  uint16_t position = getPosition(horizonPosition);
  screen[position-1] = SYM_AH_CENTER_LINE;
  screen[position+1] = SYM_AH_CENTER_LINE_RIGHT;
  screen[position] =   SYM_AH_CENTER;
```

**Comment by ShikOfTheRa** [comment]
OK - updated in repository

**Comment by ShikOfTheRa** [comment]
And thanks for guidance - I don't use this - so completely missed.

**Comment by CrazyCoder** [comment]
Thanks for the quick fix!

**Comment by ghostface** [comment]
I have that code in my build but somehow the crosshair is still not centered?
I first thought it might be related to my widescreen c800t camera but its the same on my hs1177.
Cam is running on NTSC so there should be no PAL cropping which could affect it.

Also I saw this issue https://github.com/ShikOfTheRa/scarab-osd/issues/318 and the screencaps in there show the crosshair exactly as off-centered as I have it.

I doctored an image real quick to show what I mean:

![offcenter](https://user-images.githubusercontent.com/128932/33235155-d99463ae-d232-11e7-8d7f-67b284dac8ab.png)

Any advise?

**Comment by ShikOfTheRa** [comment]
Note that many screen displays do not accurately presnet the full PAl or NTSC size so can appear off center. They are particularly variable with the height. Less common is width
You can just move them around with GUI to compensate.

**Comment by ghostface** [comment]
Thanks for the reply! At first I kinda figured the horizon would be sort of auto centered but yeah manually moving it is kinda obvious now that I think about it :)

**Comment by ghostface** [comment]
I know this is super old but I am now using 1.8 on a silverware whoop build and I no longer can move the the horizon item around in the configurator to center it. Any idea/setting I am missing?
