### ISSUE TITLE
Unable to save edited graphical layout

### ISSUE THREAD

**Issue by kelleysislander** [ShikOfTheRa/scarab-osd#181]
Hi, I am unable to get the edits to the layout in the layout editor to persist...  I posted a detailed description on fpvlabs.com and you can see the thread here:

[http://fpvlab.com/forums/showthread.php?34250-MWOSD-for-MULTIWII-NAZE32-BASEFLIGHT-HARIKIRI&p=772003&posted=1#post772003](url)

Thanks,

Bill

**Comment by ShikOfTheRa** [comment]
This was an issue with previous release. Unable to replicate in latest - and confirmation received from other testers that this is resolved
