### ISSUE TITLE
Crosshairs not on accelerometer

### ISSUE THREAD

**Issue by bigjohn141** [ShikOfTheRa/scarab-osd#185]
Would it be possible to unlink the crosshairs from the horizon bar in future releases? I like having the crosshairs just as a reference but on a lot of the newer feature of Betaflight and raceflight you have to disable the accelerometer to free up cpu. As a by product the horizon bar and crosshairs disappear.

**Comment by ShikOfTheRa** [comment]
This is in latest dev / next release...
//#define FORCECROSSHAIR            // Forces a crosshair even if no AHI / horizon used

**Comment by bigjohn141** [comment]
Great! Thank you sir!
