### ISSUE TITLE
R1.3 SP1 gui - cannot access Layout Editor

### ISSUE THREAD

**Issue by cyclingengineer** [ShikOfTheRa/scarab-osd#19]
On windows 8.1 with java 8 update 45 (i think) clicking the Layout Editor button in the gui doesn't do anything so the layout cannot be edited.

**Comment by ShikOfTheRa** [comment]
Please try latest download posted in beta release section. It should be fixed:

https://drive.google.com/a/mitel.com/folderview?id=0B2MInRUrbpWxSk9hZ3JIRXNRUU0&usp=sharing#
