### ISSUE TITLE
i  just need help

### ISSUE THREAD

**Issue by nitro20** [ShikOfTheRa/scarab-osd#191]
arduino says error 1 when i try to flash 1.6.. i have 1.5 now. the pitch degrees jumps from 44 to 100 up to 300., when the craft is only at a 45deg angle.?

**Comment by ShikOfTheRa** [comment]
Support such as is via community on fpvlab.com I cant help with anything otehr than bugs
I think from memory there are issues with 1.5 pitch / roll. No known problems with 1.6 pre-release so I would definitely recommend that
