### ISSUE TITLE
Proposal: FrSky Smartport-Protocol OUT

### ISSUE THREAD

**Issue by MarenB** [ShikOfTheRa/scarab-osd#196]
Guys, this might be a stupid idea, but I would like to share it anyway :)

Would it be possible to implement an option to output i.e. the GPS data as telemetry-data for FrSky-receivers? 
I would like to safe another arduino used as GPS-to-S-Port converter due to space limitations in my latest project.

Maybe this would be useful for others, too?

**Comment by ShikOfTheRa** [comment]
Not something planned. I suspect not feasible with remaining codespace either.
Definitely not on the roadmap... sorry
