### ISSUE TITLE
MacOS X app not working.

### ISSUE THREAD

**Issue by karman-san** [ShikOfTheRa/scarab-osd#197]
I got and error saying 'can not run app' as of MWOSD_GUI 1.6.

Worked fine with 1.5.

Running on OSX El Capitan.

**Comment by karman-san** [comment]
Found that permissions for some files inside MW_OSD_GUI.app are wrong, mostly missing execution bit. Tried to fix it by 'chmod -R +x MW_OSD_GUI.app'. Now I have a different error from OSX telling me that the app is damaged and should be trashed.

**Comment by karman-san** [comment]
Found a way to configure the MWOSD by launching manually application.macosx/MW_OSD_GUI.app/Contents/MacOS/MW_OSD_GUI from the terminal.

**Comment by ShikOfTheRa** [comment]
In the faq are some solutions for this

**Comment by jwellman80** [comment]
I was having the same issue and rebuilt and exported with processing.  You can find the .app here:
https://www.dropbox.com/s/8vqslop50d9kudh/MW_OSD_GUI.zip?dl=1

**Comment by ShikOfTheRa** [comment]
Can you let me know if it works for you

**Comment by karman-san** [comment]
Sorry for the late response. Worked fine for me. Thank you both.
