### ISSUE TITLE
Can't write config to OSD from GUI. Simulate on OSD is ON.

### ISSUE THREAD

**Issue by c4pic** [ShikOfTheRa/scarab-osd#198]
I flashed my MinimOSD with R1.6. When i connect GUI to OSD , 'Simulte on OSD' is ON and then GUI is blocked and i can't able to change or write new settings.

I  changed the line    `<entry` `key="AutoSimulator">1</entry>` from GUI.CFG file to `<entry` `key="AutoSimulator">0</entry>` , then works fine.

**Comment by ShikOfTheRa** [comment]
i intended to disbable but forgot. I need it on for development.
what FPS are you getting? Its usually a sign of a really old pc or something else hogging cpu power

**Comment by c4pic** [comment]
I run GUI in a Win 8.1 64bits Laptop / Core 2 Duo T5550 1,83Ghz / 3Gb RAM

I'm getting about 4 FPS without 'Simulate on OSD'. With 'Simulate on OSD' enabled, GUI is blocked.

**Comment by ShikOfTheRa** [comment]
I have repackaged the zip file to include it with that disabled by default.
4 fps should be OK.

Someone is building a chrome app right now to replace / provide alternative the the current GUI. No ETA, but hope it will be available for next release. He has made amazing progress with it

**Comment by c4pic** [comment]
Thank you!! Great job!
