### ISSUE TITLE
Battery voltage directily from osd doesn't change

### ISSUE THREAD

**Issue by carebear482** [ShikOfTheRa/scarab-osd#200]
Hello,

When I hook battery right into battery pads and use 5v refrence then voltage stays same or starts to drift slowly lower. What can cause this? I am using this OSD http://www.banggood.com/MXK-Power-Distribution-Board-PDB-with-OSD-BEC-Output-5V-12V-3A-LC-Filter-for-CC3C-Naze32-F3-p-1031375.html

**Comment by ShikOfTheRa** [comment]
Check FAQ #9
