### ISSUE TITLE
Cell count detection question

### ISSUE THREAD

**Issue by skaman82** [ShikOfTheRa/scarab-osd#204]
On the release notes I've read that mwosd supports autodetection of cells. I usually fly with 3 AND 4S lipos. I've configured MWOSD this way
<img width="196" alt="bildschirmfoto 2016-04-04 um 00 17 51" src="https://cloud.githubusercontent.com/assets/11768024/14235299/c6265e74-f9fa-11e5-9ee2-4f016507062b.png">

If I connect a 3S battery, I get a low voltage warning. Should it not detect now a 3 cell lipo now? And the voltage alarm setting should be a voltage per cell. Did I something wrong with the setup? How does this work?

**Comment by ShikOfTheRa** [comment]
FAQ #26 in FAQ. Just updated for you
https://github.com/ShikOfTheRa/scarab-osd/blob/master/OTHER/DOCUMENTATION/FAQ.md

**Comment by skaman82** [comment]
@ShikOfTheRa Thanks! I'll give it a try

**Comment by skaman82** [comment]
works like a charm, thank you. It would be better to activate this feature in the GUI tho :)
