### ISSUE TITLE
Voltage warning hysteresis 

### ISSUE THREAD

**Issue by KevinVecchione** [ShikOfTheRa/scarab-osd#206]
Voltage sags during high throttle maneuvers on powerful setups can briefly trip the voltage warning. A simple hysteresis implementation such as delaying the warning until voltage has been low for a certain amount of time would help filter these false positives.

**Comment by ShikOfTheRa** [comment]
Agree... added to the wish list.

**Comment by ShikOfTheRa** [comment]
Kevin - I'm going to close this as it is added to the roadmap for next full release.
