### ISSUE TITLE
Dronin support

### ISSUE THREAD

**Issue by dronophobia** [ShikOfTheRa/scarab-osd#234]
In the osx version of 1.6 i don't see dronin in config.h 
I used Taulabs msp instead, this gives inconsistent altitude.

Is support for Dronin coming in a next release?

Thank you very much for your valuable time.

**Comment by ShikOfTheRa** [comment]
dronin and tau are identical as far as mwosd is concerned.

Does your FC have baro, gps or both. And is this fixed wing or multirotor?

**Comment by dustin** [comment]
What is inconsistent in altitude?  They should be the same, though the values may be incorrect (or your altitude may not be valid).

Regardless, TL vs. dRonin doesn't make a difference here.

**Comment by ShikOfTheRa** [comment]
Will close this as duplicate of  #245 which contagins more info
