### ISSUE TITLE
Dronin Altitude incorrect + no Speed

### ISSUE THREAD

**Issue by cpusmith** [ShikOfTheRa/scarab-osd#245]
I'm not sure if I have MWOSD configured incorrectly or not but the Speed indicator always reads zero and the default Altitude reads -21 meters although it's pretty accurate in incrementing (-19 at 2 meters of height). I've added the GPS Altitude and it appears to start at 0 and increments but is not as accurate as the barometer Altitude which I'd prefer to use.

I'm using a Sparky 1.1 on a 250 frame with MWOSD 1.6 Master on a Micro MinimOSD and dRonin 2016-04-09.2 Release ("Tanto")

#234

**Comment by tracernz** [comment]
We send the wrong altitude by the looks. It needs to be inverted in the case where it comes from PositionActual.Down (PositionActual uses the NED co-ordinate system). https://github.com/d-ronin/dRonin/blob/next/flight/Modules/UAVOMSPBridge/UAVOMSPBridge.c#L461

**Comment by ShikOfTheRa** [comment]
Thanks tracernz. Doesn't sound like anything for MWOSD. 

Can someone advise if / when a patch is made available in dRonin

**Comment by dustin** [comment]
You can just close this bug.  It's a dRonin thing.  I thought it had been
fixed over there, but not sure if it's come out in a release.

**Comment by tracernz** [comment]
Issue raised to fix this.

**Comment by ShikOfTheRa** [comment]
Re-opened to keep track

**Comment by cpusmith** [comment]
Will you also be looking at the zero speed display as well?

**Comment by tracernz** [comment]
Can do, on brief inspection looks like the only place we send a speed through is the raw GPS message.

**Comment by tracernz** [comment]
@cpusmith Can you please test d-ronin/dRonin#1035 and see if it fixes your issues? Thanks in advance.

**Comment by cpusmith** [comment]
Thanks.  Will do.

**Comment by tracernz** [comment]
Confirmed fixed by @cpusmith. 👍

**Comment by ShikOfTheRa** [comment]
Brill
