### ISSUE TITLE
changes for kylin are only half complete

### ISSUE THREAD

**Issue by DerKorb** [ShikOfTheRa/scarab-osd#247]
someone added kylin250 pdb define but forgot to also add the part where it actually changes the voltagepin to a6

**Comment by jflyper** [comment]
Look like the KYLIN250 was first introduced in e0c56cc .

I think we need a PR from working code, because we don't know the configuration of input circuitry and such.

**Comment by ShikOfTheRa** [comment]
Thanks - its merged.
