### ISSUE TITLE
mw osd 

### ISSUE THREAD

**Issue by alshemali320** [ShikOfTheRa/scarab-osd#254]
hello
  am seing windows 10 ,, i am try to install my mw osd all setup went ok , except when i run the program ,, the reading osd hung at 36% and wont be complete , i redo all setting when no help ..
 best regard

**Comment by jflyper** [comment]
Need more information on the OSD hardware, MWOSD release, nature of USB driver you are using, instruction page if you followed one, etc.

BTW, did you successfully flashed the OSD with Arduino IDE?

**Comment by jflyper** [comment]
Oh, and it is better for you to ask this kind of question in the fpvlab's MWOSD thread. There are much more people around there.
[http://fpvlab.com/forums/showthread.php?34250-MWOSD-for-MULTIWII-NAZE32-BASEFLIGHT-HARIKIRI](url)
