### ISSUE TITLE
MW_OSD_GUI/application.macosx gone?

### ISSUE THREAD

**Issue by jflyper** [ShikOfTheRa/scarab-osd#268]
Looks like it was removed as a part of #261?

And the MWOSDVER was bumped to 13 so my R1.6 GUI does not talk to OSD anymore 😕 
Was there actually any EEPROM format change?

**Comment by ShikOfTheRa** [comment]
Hi - no change to layout, but unfortunately there were some release out there with bad xml file causing lockups when functions enabled. 
Wanted to force this for the last point release to make sure they didnt use an exisiting GUI. 
If it helps, I'm happy to restore the gui and downrate the ver. Its really  not an issue :)

**Comment by jflyper** [comment]
Is there any problem with MWOSDVER==13 and application.macosx ???

**Comment by ShikOfTheRa** [comment]
No - I just cant create the application

**Comment by jflyper** [comment]
Any time frame for the MacOSX GUI?

I can live with MWOSDVER reverted to 12 in my local repo, but I'd suspect the majority of the mac users can't.

**Comment by LaserLock** [comment]
you can built it yourself with https://github.com/ShikOfTheRa/scarab-osd/tree/master/OTHER/MW_OSD_GUI_SOURCE/MW_OSD_GUI

**Comment by ShikOfTheRa** [comment]
reverted :)
