### ISSUE TITLE
Support for KISS ESC Telemetry

### ISSUE THREAD

**Issue by llambkin** [ShikOfTheRa/scarab-osd#275]
Hello again Shik,

I was wondering how hard it would be to implement KISS ESCs telemetry directly to the OSD. We dont really need it on the FC, so Just having the ESC data on the OSD would be great. Even just having a combined MAH would be great.

The code is available here:
http://www.rcgroups.com/forums/showthread.php?t=2555162
There is an arduino example and a manual on the telemetry protocol.

If you are able to implement the code, I can do the testing, this will help all that run KISS ESCs, and don't necessarily run a KISS flight controller. I can modify my minim if required.

**Comment by ShikOfTheRa** [comment]
Sorry - not something planning to do - too much of a hack and work!
