### ISSUE TITLE
Mac OS MW_OSD_GUI file

### ISSUE THREAD

**Issue by mmuldoon** [ShikOfTheRa/scarab-osd#287]
Not sure if this has been addressed or not but the Mac MW_OSD_GUI file when I try and open it on my Mac is giving me this error.
![screen shot 2016-07-30 at 10 01 37 pm](https://cloud.githubusercontent.com/assets/7659668/17274314/47f5bbcc-56a1-11e6-81af-d7b59c4b8d2a.png)
Thanks

**Comment by jflyper** [comment]
There's an entry in the FAQ. Did you try?
[https://github.com/ShikOfTheRa/scarab-osd/blob/master/OTHER/DOCUMENTATION/FAQ.md](https://github.com/ShikOfTheRa/scarab-osd/blob/master/OTHER/DOCUMENTATION/FAQ.md)

**Comment by mmuldoon** [comment]
Sorry didn't see that.
