### ISSUE TITLE
FC RSSI is broken on current master

### ISSUE THREAD

**Issue by jflyper** [ShikOfTheRa/scarab-osd#288]
BF2.9 sends 0~1023 as RSSI in MSP_ANALOG.

R1.6:  [https://github.com/ShikOfTheRa/scarab-osd/blob/v1.6/MW_OSD/MW_OSD.ino#L887-L889](https://github.com/ShikOfTheRa/scarab-osd/blob/v1.6/MW_OSD/MW_OSD.ino#L887-L889)
```
      if(Settings[S_MWRSSI]) {
        sensortemp = MwRssi;
      }
```

master: [https://github.com/ShikOfTheRa/scarab-osd/blob/master/MW_OSD/MW_OSD.ino#L961-L963](https://github.com/ShikOfTheRa/scarab-osd/blob/master/MW_OSD/MW_OSD.ino#L961-L963)
```
      if(Settings[S_MWRSSI]) {
        sensortemp = MwRssi<<2;
      }
```

So the effect is, displayed RSSI is x4 of what it should be, and it consequentially made the max (back) to 255.

**Comment by jflyper** [comment]
Okay, it looks like the change was introduced as a part of LTM (#219) RSSI scaling fix ([commit fa68ff6](https://github.com/ShikOfTheRa/scarab-osd/commit/fa68ff66453ac5e56a06c61bd7f66dd7e78e9fd0)).

Proposed change is to do this scaling when the value is read from a LTM message, so the range is in coherence with MSP when ProcessSensors sees it.

**Comment by jflyper** [comment]
#289

**Comment by ShikOfTheRa** [comment]
yep. My error shifted in wrong place
