### ISSUE TITLE
MW_OSD for MacOS

### ISSUE THREAD

**Issue by Tomcatt** [ShikOfTheRa/scarab-osd#306]
I downloaded the updated Github file from here to update my Micro MinimOSD.  The Mac version isn't working.  Do I need to compile it?

**Comment by jflyper** [comment]
Can you revert to the R1.6 GUI? It should be compatible with R1.6.1.0 and latest dev master.

**Comment by Rodrigoah** [comment]
Same here, will try R1.6

**Comment by jflyper** [comment]
@Tomcatt 
> MW_OSD_GUI is damaged and cannot be opened...
Do you have this problem, too?
If so, you can fix it by modifying the permission bits.
See FAQ#4 in DOCUMENTATION for details.

**Comment by Tomcatt** [comment]
Yes, I still have the older copy.

I'll checkout that doc file tomorrow and let you know my findings.

**Comment by Rodrigoah** [comment]
@jflyper Solved with FAQ#4... Feel soooo dumb...

**Comment by ShikOfTheRa** [comment]
@Tomcatt are you OK now?

**Comment by Tomcatt** [comment]
Okay, I'll test it out later today.
