### ISSUE TITLE
The sight in the center of the screen

### ISSUE THREAD

**Issue by a6j** [ShikOfTheRa/scarab-osd#318]
Is it possible to implement a shutdown function Horizon Bar and turn a sight (of the cross) in the center?

**Comment by jflyper** [comment]
Can you elaborate?

Do you want to turn AHI (Artificial Horizon Indicator) and Airplane marker OFF? Or switch between ON and OFF?

**Comment by a6j** [comment]
Now if you need a cross in the center, you need to enable Horizon Bar. But he did not need a racing copter, but useful sight in the middle.
![1](https://cloud.githubusercontent.com/assets/15672165/18862230/5fb8c202-8493-11e6-80c4-fad58d319ef1.jpg)
![2](https://cloud.githubusercontent.com/assets/15672165/18862233/64da0f2a-8493-11e6-970d-f5f1c0e71493.jpg)

**Comment by jflyper** [comment]
You can do it by
(1) Enable FORCECROSSHAIR in Config.h (remove // at the beginning of the line).
(2) Disable Display Horizon Bar from GUI.

**Comment by a6j** [comment]
Thank you. Everything worked as needed. But it is much easier to bear this option in the GUI configurator.

**Comment by jflyper** [comment]
Glad it worked as you wanted.

> But it is much easier to bear this option in the GUI configurator.

Consider GUI as GCD. Not every option can have a place in the limited screen. (And it's kinda pain for us to keep adding GUI support for ever increasing features.)

**Comment by a6j** [comment]
Good. Thank you.
