### ISSUE TITLE
New font, like RROSD

### ISSUE THREAD

**Issue by mixMugz** [ShikOfTheRa/scarab-osd#319]
Hi there. I make new font for OSD. If possible, add for all application GUI

[Link for download](https://dl.dropboxusercontent.com/u/14462897/digital.mcm).

[Preview1](http://leproimg.com/2537397) [Preview2](http://leproimg.com/2537399)

**Comment by ShikOfTheRa** [comment]
Thanks.I like the font too. Added as one of choices in the GUI fonts folder. Source only at momet so will be there in next compiled GUI
