### ISSUE TITLE
Wrong altitude showed when using LTM telemetry

### ISSUE THREAD

**Issue by sppnk** [ShikOfTheRa/scarab-osd#324]
When using LTM telemetry the GPS altitude value is multiplied x100.

**Comment by ShikOfTheRa** [comment]
Had a veryquick look through and cant see any obvious issues. 
@digitalentity
Can you confirm if LTM sends altitude in cm?

**Comment by sppnk** [comment]
Hi, after some more tests, I have seen sometimes how the value rises. As I am testing LTM throught downlink telemetry at the same time I can see the value in EZGUI software and I see there a normal value.

**Comment by ShikOfTheRa** [comment]
Ah did you change to 100? I'll check again.

**Comment by ShikOfTheRa** [comment]
Ah yes I see it - It was *10 that confused me.
That helped. Run through again and can see the *100 error straight away :)

Corrected and in latest update in repository

**Comment by sppnk** [comment]
Great !! Thank you.

**Comment by tednv** [comment]
still seeing this in 1660 what was the change to fix it?
