### ISSUE TITLE
Innova OSD GPL Violation

### ISSUE THREAD

**Issue by btreecat** [ShikOfTheRa/scarab-osd#329]
It seems that with Furious FPV using some sort of derivative of MWOSD. They do not however provide their changes as required by the GPL, which mwosd/scarab-osd is licensed under. 

I think we should start contacting them regarding the release of their modified source. This could make integrating vtx changing easier for other hardware as well.

**Comment by ShikOfTheRa** [comment]
They are  preparing code for release.

Note broadly equivalent source is available here:
https://github.com/PickwickGroup/scarab-osd/tree/impulserc_vtx

**Comment by btreecat** [comment]
Yes they emailed me back finally letting me know they are interested in
complying with the licens

**Comment by ShikOfTheRa** [comment]
Closing this and updates will be in #327
