### ISSUE TITLE
Clock running slow

### ISSUE THREAD

**Issue by VirtualEnder** [ShikOfTheRa/scarab-osd#33]
I just noticed this by accident when I was editing some video from my DVR.  The timer is runing significantly slow. From arm to disarm in the video is just over 4 minutes, and the OSD is showing 3:31.  It gets even more pronounced on longer runs.  After noticing I started paying attention, and a flight today the OSD said 5 minutes and the timer on my transmitter said almost 7.

This is on stable 1.3 running on a full size minimOSD.  Also as a side note, the mAh readings are off as well due to the clock runing slow.  They seem to be high by the same ratio even when the instantaneous readings are accurate.

**Comment by ShikOfTheRa** [comment]
Hopefully realised in 1.4 
Issue has been there day one, but I think recent improvements and changes to sync code has highlighted the problem much more.

**Comment by therippa** [comment]
I'm having this problem too, it's telling me ~2:00 after flights that are ~5:00.

**Comment by VirtualEnder** [comment]
I just uploaded 1.4 r1.1 and it seems to have solved the problem. Thanks!

**Comment by therippa** [comment]
Where are you finding 1.4 r1.1?  I'm not seeing that branch/tag.

**Comment by ShikOfTheRa** [comment]
HAd 2 reports this is fixed - so closing. Thanks...
