### ISSUE TITLE
Unable to select LOADFONT_DEFAULT option

### ISSUE THREAD

**Issue by RBeaubien** [ShikOfTheRa/scarab-osd#332]
I get a number of errors when I uncomment the LOADFONT_DEFAULT option beginning with this error:

<path>\MW_OSD.ino: In function 'void setup()':
MW_OSD:159: error: 'initRSSIint' was not declared in this scope
   initRSSIint();

What am I doing wrong?  I am using Arduino 1.6.11

Thanx,

**Comment by ShikOfTheRa** [comment]
Confirmed this issue with 1.6.12

I think the issue is with line length. I have amended and can confirm it compiles for me with 1.6.12
I also uploaded three different font types OK to test via config.h.

Please can you try latest from repository to confirm?

Thanks

**Comment by RBeaubien** [comment]
That fixed it.  Thanx.

**Comment by ShikOfTheRa** [comment]
Thanks for testing!
