### ISSUE TITLE
How to exit debug screen?

### ISSUE THREAD

**Issue by DangerD256** [ShikOfTheRa/scarab-osd#333]
![0-02-05-13af3a6a740bbbad441f21c8211c72f6499cac7f00d8d903634b1f614c578731_full](https://cloud.githubusercontent.com/assets/17032489/20270105/70d43956-aa8e-11e6-9ecd-8725fd6a8125.jpg)
How can i exit from this screen?

**Comment by jflyper** [comment]
Looks like you have uploaded the current development master.

You can't exit the debug screen. You have to disable debug options at the top of the Defs.h file and upload the sketch again.

@ShikOfTheRa Can you disable the relevant debug options and put the master into production state?

**Comment by ShikOfTheRa** [comment]
OK done
