### ISSUE TITLE
can't compile on arduino 1.6.12

### ISSUE THREAD

**Issue by csurf** [ShikOfTheRa/scarab-osd#334]
seems there's an issue with latest arduino (1.6.12 in my case) whereby the function definition prototypes aren't correctly extracted from the source code. To reprooduce, install latest arduino & try to compile.

**Comment by jflyper** [comment]
@csurf Can't reproduce it locally with MacOSX 10.11.6, Arduino 1.6.12, with current master (8b1a291).
<img width="606" alt="screen shot 2016-11-16 23 58 22" src="https://cloud.githubusercontent.com/assets/14850998/20352156/a9e47a86-ac59-11e6-8e74-0158052de083.png">

**Comment by jflyper** [comment]
@csurf We believe the problem is fixed. Can you try the latest dev master?
