### ISSUE TITLE
Incompatibility with Arduino 1.6.10 and later

### ISSUE THREAD

**Issue by jflyper** [ShikOfTheRa/scarab-osd#335]
Arduino 1.6.10 and later decided to go strict on forward declarations, or effectively doing the same thing.

Related: #334 #332

**Comment by ShikOfTheRa** [comment]
great. I see in reference it compiles OK for you n mac though? I am travelling so not enough broadband allowance to download and try myself. Will be a couple of weeks before can look at

**Comment by jflyper** [comment]
@ShikOfTheRa 
I think I was fooled by multiple arduino instances when I did that testing for #334.

The issue is present and consistent among 1.6.10 and later in my environment.

**Comment by jflyper** [comment]
So, does anybody know what has happened in 1.6.10?

Looks like Arduino preprocessing (merge all ino, insert some includes and collect declarations) is corrupt or has changed in some way.

**Comment by ShikOfTheRa** [comment]
Weird. 

I installed 1.6.12 and clicked the remove old version .option Rebooted and can compile OK with no errors. Just also tried a manual delete and reinstall no issues.

Cant find any other versions of arduino on my pc and only 1 version of avrgcc which is  4.9.2

**Comment by ShikOfTheRa** [comment]
Can you confirm if the latest compiles?

**Comment by jflyper** [comment]
It compiles! What did you do?

**Comment by sppnk** [comment]
May be it has something to do with [this weird arduino ide](https://github.com/arduino/Arduino/issues/2989) issue?

**Comment by ShikOfTheRa** [comment]
I think there must have been some IDE changes with max characters on a single line so I simply split the fontdata line into 2.

It took some finding......

**Comment by jflyper** [comment]
@ShikOfTheRa Thanks for your findings! Closing.
