### ISSUE TITLE
1.6.5.0 - FULLAHI compile error

### ISSUE THREAD

**Issue by nhadrian** [ShikOfTheRa/scarab-osd#338]
Hi,

I'd test the latest 1.6.5.0 but I got a compile error when FULLAHI is enabled.

Regards Adrian

![image](https://cloud.githubusercontent.com/assets/5570527/21043699/7f105f22-bdf8-11e6-9d21-5acdc0b971ee.png)

**Comment by ShikOfTheRa** [comment]
oh yep - missing text - should be  #elif defined FULLAHI

Updated repo - prob easier just to add word in to yours
