### ISSUE TITLE
config.h comments misleading

### ISSUE THREAD

**Issue by NicoLoco** [ShikOfTheRa/scarab-osd#34]
in config.h, comments that indicate what the #define do are misleading

//#define MULTIWII_V24              // Undefine this if you are using MW versions 2.4

It should say either "define" or "uncomment"

**Comment by ShikOfTheRa** [comment]
Fair comment !! will change!

**Comment by ShikOfTheRa** [comment]
Updated in github. Too late for latest beta but will be in 1.4 full. thanks...
