### ISSUE TITLE
Max Current and Min Voltage

### ISSUE THREAD

**Issue by maahinberi** [ShikOfTheRa/scarab-osd#342]
Would it be possible to display the Max current and Min voltage alongside the instantaneous current and voltage?

**Comment by dustin** [comment]
It's certainly possible, but I don't know that that'd be useful without
some kind of filtering (e.g., the lowest the voltage has been for more than
five seconds, etc...).

**Comment by maahinberi** [comment]
Ok, I just saw in the Release notes of 1.6 that the Max Amps is shown in flight summary. Min Volts could also be shown

**Comment by ShikOfTheRa** [comment]
Have added to the wish list / roadmap. I don't have any immediate plans to add this in though
