### ISSUE TITLE
Horizon Bar is showing  LON LON LON &~ LON LON LON

### ISSUE THREAD

**Issue by patrickpoirier51** [ShikOfTheRa/scarab-osd#345]
Running CleanFlight latest release on a F3 Based FC.
Just uploaded version MWOSD R1.6 with Standard Config.h on a Mini OSD.

Problem:
Looking and the Horizon , it is not showing bars and dots but:
LON LON LON &~ LON LON LON
And this is sequentially displaying (depending on the angle):
LON - LAT - MAH -KMH - KNTH -MS -THR -VEL -ALT

Never used this software before, might have missed something ? Please advise

**Comment by advancetom** [comment]
U must use a 5Volt Programmer!  got the same Problem

**Comment by patrickpoirier51** [comment]
Thanks for the tip , I tried another Programmer and its OK now :-)

**Comment by patrickpoirier51** [comment]
Might be interesting to add this on the install guide ?
Have an FTDI breakout board (which usually connects to a USB port)  with **sufficient power (5 Volts) and** the proper headers and to connect to your OSD hardware.

**Comment by jflyper** [comment]
The requirement for the good 5V source when flashing (and probably writing EEPROM) is known for a long time, but yes, it's not mentioned anywhere in the DOCUMENTATION.
