### ISSUE TITLE
MWOSD GUI Mac OS X 10.11

### ISSUE THREAD

**Issue by dan13373** [ShikOfTheRa/scarab-osd#346]
Hi Shik,

I have tested the micro minimOSD with an FTDI to USB converter on my Mac with the correct drivers (dev/usb.serial is the port). The Arduino loads the MWOSD.ino firmware on the minimOSD successful without an error. 

I then restarted my Mac and then started the MWOSD GUI by disabling the Gatekeeper in order to make it start. I set the BAUD Rate to 57600 (as the Arduino IDE was using) and tried to connect to the usb.erial (stated in the GUI like that)...but it keeps saying "Waiting for OSD". I checked the wiring - but I guess this must be correct since the upload of the firmware was successful.

Is there a chance to check/set the Port Setting like in Arduino IDE?

Edit: and yes, I cleared "EEPROM" before.

Best,
Dan

**Comment by jflyper** [comment]
Default speed is 115200. Try it.

Arduino IDE 's speed is for boot loader. MWOSD as a standalone software has it's own speed, which defaults to 115200 unless you tweak it in Config.h.

**Comment by dan13373** [comment]
Not working :( but thx

**Comment by ShikOfTheRa** [comment]
@dan13373 I'm not clear from comments- did you change GUI baud to match the OSD? Its not obvious - have to click on com settings button to show baud rate option.

**Comment by dan13373** [comment]
Yes I have tried that.
How long to wait until the GUI should respond?

**Comment by dan13373** [comment]
Edit:
I changed to match OSD and edited the config

**Comment by ShikOfTheRa** [comment]
Less than 10 secs. enough time for any reboot and startup delays in the code..

just a thought I get this sometimes with OSDDOGE / BROSD style boards when teh FC is connected and I forget to disconnect. I done it today... several times!

**Comment by dan13373** [comment]
It is the Micro MinimOSD.Just connected 5V, GND TX and RX.
I will flash it again.

**Comment by ShikOfTheRa** [comment]
Weird. Suggest start with config.h baud at 115k and gui at 115k to start. Thats default. Once all good maybe try them both at another baud

**Comment by dan13373** [comment]
Will Don and report

**Comment by dan13373** [comment]
Troubleshooting Steps:
1) Cleared EEPROM
2) In config changed BAUD Rate to 57k and 115k (before changing, started at 1)
3) Restarted Mac and unplugged USB Adapter
4) Opened GUI and changed comm settings

No Luck. Still says "Waiting". But the Upload in Arduino works all time. Is there something I miss?

**Comment by ShikOfTheRa** [comment]
send email to gary@flypix.co.uk for next step...

**Comment by jflyper** [comment]
That's weird...

Can you download the fresh scarab_osd dev package and start from download the sketch?

**Comment by brandonhill** [comment]
Having same issue..

**Comment by kenw001** [comment]
Same issue here. Any solution update?
Thanks!
