### ISSUE TITLE
Cannot open GUI - Error missing "lib" folder

### ISSUE THREAD

**Issue by HughAV** [ShikOfTheRa/scarab-osd#349]
I am trying to edit the osd on my diatone sp3 vtx. runs mwosd. cannot get gui to open. message says "lib" folder missing. Is this not a part of the download?

**Comment by jflyper** [comment]
Can you elaborate? Windows 7, 10, other? MacOSX? What's the MWOSD_GUI version? Screen shot of the message?

**Comment by HughAV** [comment]
thank you for replying so fast! Windows 10, most recent download of MWOSD,
Github messenger would not let me post the snip. here it is:

[image: Inline image 1]

**Comment by ShikOfTheRa** [comment]
have you tried 32 bit and 64 bit versions? Just as fyi, the 32/64 bit doesn't refer to windows you are using. Its anctually the jave component. I tried 32 bit and its working for me.

**Comment by ShikOfTheRa** [comment]
@HughAV are you working now?

**Comment by HughAV** [comment]
Thanks for following up. Have been busy, and have not had a chance to get
back in and try. I will let you know.

**Comment by ShikOfTheRa** [comment]
Closing this for now. If have continued issues please raise on support forum. Thanks!

**Comment by HughAV** [comment]
Figured it out! Issue with my PC...

**Comment by ShikOfTheRa** [comment]
OK - thanks for feedback
