### ISSUE TITLE
enum Setting_ parameters

### ISSUE THREAD

**Issue by RBeaubien** [ShikOfTheRa/scarab-osd#352]
I'm not sure where else to ask this.  I need to change some defaults for flashing and I'm not sure what some of the parameter names are used for.  I'm looking for the Voltage Use FC and Amperage Use FC parameters.  Can someone tell me which ones they are?

**Comment by ShikOfTheRa** [comment]
@RBeaubien 
are you sorted now? Need any more info?

**Comment by RBeaubien** [comment]
Yes.  Thank you.

**Comment by ShikOfTheRa** [comment]
Brill - thanks!
