### ISSUE TITLE
KISS mAh not updating when using separate current sensor.

### ISSUE THREAD

**Issue by RBeaubien** [ShikOfTheRa/scarab-osd#358]
I have fixed and tested a bug in the KISS current sensor code.  How do you want me to post the fix?  I'm new to github and I would like to do it the correct way.  The fix is in MW_OSD.ino starting about line 309

Old code:
```
    if (Settings[S_AMPER_HOUR]) 
    #ifndef KISS
      amperagesum += amperage;
    #endif    

```
New code:
```
    if (Settings[S_AMPER_HOUR]) 
    {
      #ifndef KISS
        amperagesum += amperage;
      #else 
        if (!Settings[S_MWAMPERAGE]) 
          amperagesum += amperage;
      #endif   // KISS
    }

```
This fixes a bug that does not total mAh used when using a separate current sensor from the ESCs.

**Comment by ShikOfTheRa** [comment]
Excellent - many thanks. Have updated the reposirory. 
Happy to take code snippets like this to save learning github
