### ISSUE TITLE
move GUI to new platform

### ISSUE THREAD

**Issue by csurf** [ShikOfTheRa/scarab-osd#365]
I'm completely fed up with the java/process-based GUI. Can we please try to come up with something better? Even if it's just a basic config app, anything would be an improvement over the existing GUI. 

I vote for a simple chrome app that sends the OSD config over serial. We could use one of the existing 'configurator' apps for betaflight/cleanflight/baseflight as a basis for building the app. The most difficult part would be building the graphical 'screen layout' tool, but I'm sure we could find a solution for this.

Any thoughts?

**Comment by ShikOfTheRa** [comment]
@csurf 
Yes I hate it more than most... -someone is just finishing one off. ready for release with 1.7

I am going to close this so don't get lots of mails.

Attached screenshot. Its developed completely from ground up and will not be open
mail gary@flypix (dot co dot uk) if want to try.


![capture](https://cloud.githubusercontent.com/assets/11336532/21944236/06ed6ba2-d9cd-11e6-8927-c67fdd7d3fc4.PNG)
