### ISSUE TITLE
 list of supported software

### ISSUE THREAD

**Issue by mahowik** [ShikOfTheRa/scarab-osd#367]
you can also include my fork to the list of supported software
https://github.com/mahowik/mahowii

**Comment by ShikOfTheRa** [comment]
Wow. There’s a blast from the past!! MultiWii and mahowik!

Some interesting developments there. Some of those vids showed some excellent position hold.

I don’t suppose this would fit on a 328?? 
Only have one multiwii copter. I’m resisting updating it!!


Have updated the multiwii line and included url to your repo. Hopefully it will make a few other look.

**Comment by mahowik** [comment]
Thanks a lot.

With 328 it's possible to fit but without GPS.

Sorry but I didn't found the description update anywhere. Did you forgot to commit? :)

**Comment by ShikOfTheRa** [comment]
I put in config.h like this

//#define MULTIWII                  // Uncomment this if you are using latest 2.4 MULTIWII / MAHOWII  (https://github.com/mahowik/mahowii)

I thought so. 
I'll have a look. I do have one of these.. http://www.multiwiicopter.com/products/paris-v5r3-multiwii-with-full-osd-gps-mag-board

**Comment by mahowik** [comment]
thanks a lot
