### ISSUE TITLE
1.6.7 Canvas mode (MSP_DISPLAYPORT) going OoS

### ISSUE THREAD

**Issue by jflyper** [ShikOfTheRa/scarab-osd#371]
There has been multiple reports of 1.6.7 showing asterisk with screen cleared upon entry into canvas mode.

https://www.rcgroups.com/forums/showpost.php?p=36754674&postcount=44074

1.6.5 is okay.

**Comment by jflyper** [comment]
Strange that no MSP_DISPLAYPORT message seems to be understood after displaying the asterisk.

**Comment by ShikOfTheRa** [comment]
My error I think. Cleaning up compiler errors for unused variables...
Just undone...

**Comment by jflyper** [comment]
It actually was my fault to make this an option. I should have coded the attribute field as mandatory on both sides!!!

**Comment by ShikOfTheRa** [comment]
No - definitely my fault. I haven't tested to confirm. Will do this week. Could do with a copter of each type to verify everything without constantly rebuilding...
