### ISSUE TITLE
can not navigate in menu

### ISSUE THREAD

**Issue by robschii** [ShikOfTheRa/scarab-osd#372]
i use microminim osd from banggood  and i use the last beta.

i can open the menu  mitch trottle stick middle and pitch foward  an also exit  but i can not change the  page   witch yaw right and trottle middle    like in the release 1.6

**Comment by ShikOfTheRa** [comment]
That's strange - its working for me 

values sent from TX must go outside these values (which can amend in globalvariables:
#define MAXSTICK         1850
#define MINSTICK         1150

They are quite high, but in line with how shoudl be configured with a normal FC.
Also worth checking that rates are not enabled.

Odd thing is can enter the menu.... which uses same values!

**Comment by ShikOfTheRa** [comment]
Just to be sure - what controller do you have set in config.h
