### ISSUE TITLE
xjt transmitter telemetry, Will not display osd over video.

### ISSUE THREAD

**Issue by triolus** [ShikOfTheRa/scarab-osd#377]
No option to take xjt transmitter s-port telemetry to osd. Osd will not overlay over video. when video is off the osd data is available. composite video to goggles/monitor being hacked into OSD. This is to remove the osd from the craft. Requesting direct frsky s-port to OSD option without flight processor in between.

**Comment by jflyper** [comment]
@triolus 
Are you talking about receiver side OSD?

**Comment by ShikOfTheRa** [comment]
I think so. Not to bad to do, but I suspect requires hardware inverted if its like rest of FRSKY...

I don't have any plans as no time. Added to development wishlist if anyone else can pick this up

**Comment by triolus** [comment]
Yes. I do not know if the FRSKY xjt is set up to just transmit proper fsky telemetry data or if it is only designed for their own monitor. I made a small error and will retest;I was having the OSD transmit go back to the XJT. It gives an option for which hookup: uart or frsky, and will test the uart option without transmitting back.

**Comment by ShikOfTheRa** [comment]
I am closing this to keep the outstanding issues list clean.
It is captured on the list of requests should anyone want to pick this up.
I did some googling and there do appear to be some other OSD options out there for you.
