### ISSUE TITLE
Quick Q.

### ISSUE THREAD

**Issue by jflyper** [ShikOfTheRa/scarab-osd#378]
I see completely duplicate block of defs in `Defs.h`, under `BETAFLIGHT2`.

Is this intentional?

**Comment by Robinhuett** [comment]
I guess the second block should be `BETAFLIGHT3` since it is missing from `Defs.h`.
But still it's a duplicate so `BETAFLIGHT2` could be used to define `BETAFLIGHT3` or could be removed entirely.

**Comment by Robinhuett** [comment]
This would fix it: #380

**Comment by ShikOfTheRa** [comment]
Yep - ^^ 
Trying to remember if there was a difference between 2 and 3...

**Comment by jflyper** [comment]
@Robinhuett Ack!

@ShikOfTheRa It was a total mystery for me :)
