### ISSUE TITLE
FC_VOLTAGE_CONFIG vs BETAFLIGHT

### ISSUE THREAD

**Issue by fape** [ShikOfTheRa/scarab-osd#389]
Is there any reason why FC_VOLTAGE_CONFIG is not usable with BETAFLIGHT? Only for CLEANFLIGHT and BASEFLIGHT (see: [Def.h](https://github.com/ShikOfTheRa/scarab-osd/blob/6f3156f4083d17595e35bf4555df8d34ad5cb9f5/MW_OSD/Def.h#L509), [Serial.ino](https://github.com/ShikOfTheRa/scarab-osd/blob/44dfbd13ce4bf3a552838979c7ce6fb803389ed6/MW_OSD/Serial.ino#L546))
As far as is see the relevant part of the msp protocol (MSP_MISC) is the same in [Cleanflight](https://github.com/cleanflight/cleanflight/blob/master/src/main/fc/fc_msp.c#L817), [Baseflight](https://github.com/multiwii/baseflight/blob/e582e0ce6321b7dd2293a60264e1040d0cbac5a4/src/serial.c#L663) and [Betaflight](https://github.com/betaflight/betaflight/blob/master/src/main/fc/fc_msp.c#L817)

I added `|| defined(BETAFLIGHT)`to [Def.h](https://github.com/fape/scarab-osd/blob/fape-v1.6.8.0/MW_OSD/Def.h#L526), and it is working.
If there is no special reason I can send a PR about it ;)

**Comment by ShikOfTheRa** [comment]
No reason. I think it was added before betaflight became popular. Never used myself. Feel free so Submit or I'll do next week when get bavk
