### ISSUE TITLE
move GUI code to separate repo

### ISSUE THREAD

**Issue by csurf** [ShikOfTheRa/scarab-osd#391]
I realize that the old GUI is kinda junky & overloaded, and will probably soon be replaced by the chrome app. However, in the meantime, how about sending it to its own, separate repo?  

It would make it much easier to work with the GUI code, and would also make it easier & quicker for users to clone the the MWOSD repo (wouldn't have to deal with a massive download due to GUI stuff). 

Also, it would help to remove all of the extra stuff from the platform-specific builds (from processing app) & simply have the raw code & data files placed in the repo.

Does this sound reasonable?

**Comment by ShikOfTheRa** [comment]
Agree. Was heading that way soon. Now is as good a time as any. I want to repackage 1.6 with new gui as well. 
Will do this week

**Comment by ShikOfTheRa** [comment]
It is done:

https://github.com/ShikOfTheRa/scarab-osd-gui

I think its at end of its life. 
I'm not planning to keep it in updated anymore. Haven't used it for some months now.
