### ISSUE TITLE
Allow MSP sending voltage and amps to FC

### ISSUE THREAD

**Issue by sppnk** [ShikOfTheRa/scarab-osd#393]
As MWOSD can take variables from FC like RSSI and others, why dont allow the reverse thing? Could be done? (of  course FC should to be able to take them).

This is because in many setups the volts and amps are only in the OSD, but sometimes we fly the same airplanes w/o vtx, third view, and would be nice the FC to have this (for telemetry at least).

I will open the same request in INAV repo.

What do you think?

**Comment by ShikOfTheRa** [comment]
Can be done - if can convince iNAv guys. 
Think it will be low on their list as could connect direct to the FC in most cases?

**Comment by sppnk** [comment]
Hi, I close this as I am taking the values directly in the FC. I guess it is better and I dont know if the effort to modify MSP worths this. Closing...
