### ISSUE TITLE
Cannot connect GUI to SPRF3 with integrated OSD

### ISSUE THREAD

**Issue by Fluburtur** [ShikOfTheRa/scarab-osd#396]
I have a SPR F3 board from banggood, I tried to flash the latest version of MWOSD onto it and succeeded (but didn't find "Inav" in the options so I had to select cleanflight).
The flashing succeeded but I can't connect to the board using the GUI on windows 7 64 bits.

**Comment by ShikOfTheRa** [comment]
Try this one:
https://github.com/ShikOfTheRa/scarab-osd/tree/master/MW_OSD_GUI

**Comment by Fluburtur** [comment]
It worked, thank you very much!
