### ISSUE TITLE
R1.7  not conecting GUI in mode Standalone-OSD.

### ISSUE THREAD

**Issue by isabido** [ShikOfTheRa/scarab-osd#401]
Hi guys, I'm using version 1.7, to use standalone OSD with GPS.

I followed this guide:
Http://intofpv.com/t-osd-standalone-gps

If I enable the option "#define GPSOSD_UBLOX" I can not then access it with the GUI for its configuration.

Any suggestions?

Thank you!

**Comment by ShikOfTheRa** [comment]
1 - are you using same baudrate on OSD and GUI
2 - GPS must be disconnected when connecting to GUI

**Comment by isabido** [comment]
1- Yes, the baudrate is the same in the GUI.
#define BAUDRATE 115200.

2- The GPS is obviously disconnected.

I have already commented that just disabling the UBLOX support works correctly.

**Comment by ShikOfTheRa** [comment]
Ok thanks. I will check first thing in morning....

**Comment by ShikOfTheRa** [comment]
Bug confirmed. Will get this fixed ASAP.

**Comment by isabido** [comment]
Thanks for your confirmation, meanwhile version 1.6 is not affected?

Regards!

**Comment by ShikOfTheRa** [comment]
I think 1.6 will be same. I think I understand the issue. Trying some options today...

**Comment by ShikOfTheRa** [comment]
OK - made amendment to OSD code. I am unable to test with GPS chip at moment to confirm nothing is impacted, but it looks OK on simulator...! Please try.

https://github.com/ShikOfTheRa/scarab-osd/archive/master.zip

**Comment by ShikOfTheRa** [comment]
Confirmed by others this is now working too

**Comment by isabido** [comment]
Confirmed, works correctly. I have opened a new issue. Does not display correctly with "arrows" the address to home. Instead it shows "LETTERS"

I try to load the fonts, and it disconnects when it reaches 10%.
