### ISSUE TITLE
What chip is in the HGLRC AIO F3 V4?

### ISSUE THREAD

**Issue by HughAV** [ShikOfTheRa/scarab-osd#405]

**Comment by ShikOfTheRa** [comment]
I think this is posted in wrong place. It doesnt run MWOSD.
At a guess ...  F3 chip! and max7456 for video

**Comment by HughAV** [comment]
it is an all in one fc/pdb/osd/vtx that has mwosd running on it.

**Comment by HughAV** [comment]
Thank you!
