### ISSUE TITLE
Failed to upload fonts.

### ISSUE THREAD

**Issue by isabido** [ShikOfTheRa/scarab-osd#406]
Does not display correctly with "arrows" the address to home. Instead it shows "LETTERS"

I try to load the fonts, and it disconnects when it reaches 10%.

This is the version used.

https://github.com/ShikOfTheRa/scarab-osd/archive/master.zip

**Comment by ShikOfTheRa** [comment]
Can you advise what changes you make to config.h?

**Comment by isabido** [comment]
Something like that...

http://intofpv.com/t-osd-standalone-gps
#define MINIMOSD 
#define GPSOSD_UBLOX 
#define FIXEDWING
#define BAUDRATE 115200

Thanks!!

**Comment by ShikOfTheRa** [comment]
Ah .. ok. I have an idea.

**Comment by ShikOfTheRa** [comment]
Bug confirmed. Thanks for reporting. 

This would impact UBLOX and MTK users. Very few which is possibly why not noticed before.
Its actually a bug in chrome that OSD is trying to workaround. Unfortunate side effect I did not think about..

Fixed and  uploaded into github. Please test and advise if OK.

**Comment by isabido** [comment]
Thank you for your prompt response, I will not be able to confirm until next weekend.

I'm sorry for the delay, but for work matters I'm not possible.

**Comment by ShikOfTheRa** [comment]
OK - no hurry.
I could replicate and the update worked for me. Hopefully will do for you to

**Comment by eephyne** [comment]
Hello, sorry to ask on a closed issue but did you add the fix in the last zip 1.7 ?
I have the exact same issue (standalone and UBLOX) and The version I use is the zip dowloaded on the website.
I do not mind using the git repo but wanted to check first if that was useful.

**Comment by eephyne** [comment]
I did not test the osd but the upload of the font was succesful (ftdi keep blinking till the end and gui not disconnected.
Thanks @ShikOfTheRa for your time and great software

**Comment by ShikOfTheRa** [comment]
Great! glad its working OK
