### ISSUE TITLE
mwosd problem

### ISSUE THREAD

**Issue by hugges** [ShikOfTheRa/scarab-osd#412]
in the screen for mwosd it opens but a error message 
says
"gui version does not match osd version-use correct gui version or update osd"
using w10  in chrome an using mwosd 1.5 i have tried mwosd 1.6 but it will not open

**Comment by ShikOfTheRa** [comment]
Version on OSD must match the GUI - this is to ensure settings are consistent between versions and prevent issues. 
If you are using 1.5, you must use the 1.5 GUI from here:

https://github.com/ShikOfTheRa/scarab-osd/blob/master/OTHER/DOCUMENTATION/Downloads.md

**Comment by ShikOfTheRa** [comment]
ok now?
