### ISSUE TITLE
Add a CLEANFLIGHT2 define to the Config.h file

### ISSUE THREAD

**Issue by McGiverGim** [ShikOfTheRa/scarab-osd#416]
The Cleanflight 2.x code now is exactly the same as Betaflight 3.1.7, so it must act exactly as the BETAFLIGHT (or BETAFLIGHT31) definition.

The easier solution is to add a `#define CLEANFLIGHT2` to the `Config.h`, and maybe a:
```
#ifdef CLEANFLIGHT2   
  #define BETAFLIGHT31
#endif
```
to the `Def.h`.

But I don't know if this is a correct solution, o is maybe cleaner modify all the conditions where the BETAFLIGHT31 appear to add the CLEANFLIGHT2 too.

**Comment by McGiverGim** [comment]
I've seen too that now in `Def.h`:
```
#ifdef CLEANFLIGHT    //set up latest at time of release
  #define CLEANFLIGHT190
#endif
```
So I suppose that `CLEANFLIGHT must change to point to the new CLEANFLIGHT2 definition too.

**Comment by ShikOfTheRa** [comment]
Yep - planning to do a bunch of changes like this next week.

**Comment by ShikOfTheRa** [comment]
Bit longer than a week - but its done in main repository. GUI hex distributions will be updated after made a few more additions. Enough to release..

**Comment by McGiverGim** [comment]
Thanks! I will test it ASAP ;)

**Comment by ShikOfTheRa** [comment]
So normal CLEANFLIGHT define invokes v2 support. If want earlier ones need to enable CLEANFLIGHT190
