### ISSUE TITLE
Default Font unreadable after Upload

### ISSUE THREAD

**Issue by Creautre** [ShikOfTheRa/scarab-osd#417]
I flashed MWOSD via Arduino IDE onto the MicrominimOSD Board. [ I didn't do EEPROM_CLEAR prio to this ].

Everything looked fine except that I had the wrong Symbols. Instead of battery I had an Arrow etc. so I used MWOSD Configurator and connected to the OSD via Serialpassthrough through my SPRacing F3 Evo board running Betaflight.

After I connected I used the "Change" button below "FONT:" and chose the default Font, selected it and hit Upload. Afterwards everything seemed to be in the right place but absolutely unreadable. 

I tried using EEPROM Clear on Arduino IDE and reflashing the firmware over and over again but it never worked [ desoldered from my Circuit of course ].

I managed to fix the Issue by Using the "FLASH" function of MWOSD Configurator. I first uploaded ClearEEPROM, then Bold font installer and then "Default minim Betaflight 1.7.1". For test purposes I used the first Font update method that messed everything up and it happened again. Exact same issues. After doing my procedure again, everything works fine.

You can check my thread to see the whole process and how it looked 

http://intofpv.com/t-microminimosd-not-programmable

Hope you can fix this issue or tell me what i did wrong

**Comment by ShikOfTheRa** [comment]
This has been resolved by app update. Confirmed by one of the users
