### ISSUE TITLE
32-bit: MW_OSD_GUI.exe crashes with "Unspecified Error"

### ISSUE THREAD

**Issue by chrisinvb** [ShikOfTheRa/scarab-osd#42]
When double clicking on MW_OSD_GUI.exe inside of the /application.windows32/, the following error message appears:

"Unspecified Error"

![image](https://cloud.githubusercontent.com/assets/12338530/7536476/333b3dc4-f55e-11e4-9f0c-eda6424a41ff.png)

There is no "C:\ProgramData\Oracle\Java\javapath\javaw.exe" path on my computer.

**Comment by chrisinvb** [comment]
To get the executable to run, I copied the MW_OSD_GUI.bat from the /application.windows64/ into the /application.windows32/ folder and ran the MW_OSD_GUI.bat so that the correct java libraries would load.

**Comment by VirtualEnder** [comment]
This is a pretty common error with Processing code.  It has to do with a change in the way oracle handles updating the local $PATH system variable.  Adding the non-aliased path (the path showing there is a shortcut, not the actual path) to your java installation also solves the problem.

**Comment by ShikOfTheRa** [comment]
Added to FAQ #20
https://github.com/ShikOfTheRa/scarab-osd/blob/master/DOCUMENTATION/FAQ.md
