### ISSUE TITLE
Platformio env names vs Platformio ide

### ISSUE THREAD

**Issue by fape** [ShikOfTheRa/scarab-osd#422]
Platformio ide does not find any environment. I got "empty projects" warning.
Because env names contain `'.'` (dot) character. [Only `[a-z0-9_]+` is allowed in env names.](http://docs.platformio.org/en/stable/projectconf.html#projectconf-section-env). If I replace all the dots in `platformio.ini` to `'_'` and everything works fine in the ide. Unfortunately it works from command line with dots :S

I can create a PR with new/replaced platformio.ini. But I think it may need lot more changes eg from configurator side as well. (Or replace `'_'` back to `'.'` in `.travis.yml` ?)

**Comment by ShikOfTheRa** [comment]
Actually I only use it to build hex files - so cli ok for me! 

At some point I will use because not all environments compile - and want to make it compatible with both. If not in a hurry I will make all changes in about 3 weeks?

**Comment by fape** [comment]
Thanks. I can live with my workaround some more weeks ;)

**Comment by ShikOfTheRa** [comment]
meh, sorry about this, but the re-work of the GUI to accommodate means not going to be able to implement.

It was an unknown consequence of the decision to use "," as separator, although never thought anyone would use the files for normal IDE use. Was only ever intended to create the hex files for deployment files.

**Comment by fape** [comment]
No problem, take your time. I can live with the workaround (replace all) but basically now I'm busy with other drone related development: eg  [voroshkov/Chorus-RF-Laptimer](https://github.com/voroshkov/Chorus-RF-Laptimer)

**Comment by ShikOfTheRa** [comment]
Ok I'll close this as trying to close out all issues ready to restart developement- but have put it on the "To do" list managed on "the wiki

**Comment by ShikOfTheRa** [comment]
Very cool project. I will look now. I always wondered if possible to switch frequencies and monitor fast enough - or if have to have separate rx for each frequency.
