### ISSUE TITLE
Acro/level mode distorts OSD

### ISSUE THREAD

**Issue by Markuzzzz** [ShikOfTheRa/scarab-osd#432]
Hey Guys, I am testing the MW Osd for Kiss. I have a strange error going on. When ever I use level/acro mode selection using a switch on my TX the osd disappears entirely. Not matter on which Aux I set level/acro mode in the Kiss Gui. Anybody having the same problem? Shouldnt it react only on AUX4?

Tried 1.6.8 and the newest beta of 1.7 for Kiss from github.

**Comment by dustin** [comment]
This will happen for a couple reasons:

1. You are browning out your max7456 chip (dipping below 5V will reset its state).
2. You've got an OSD switch configured that happens to match what's being sent.

The second condition could also be met by an MSP bug coming from KISS.

**Comment by Markuzzzz** [comment]
Pretty sure the first reason isn't the case. OSD doesn't restart and doesn't go to start menu/screen, but goes back to the normal osd screen. I figure it's the latter, in that case there ain't nothing to do but wait for a fix by the KISS team?

**Comment by ShikOfTheRa** [comment]
For KISS, IIRC MWOSD only supports Screen switching from an RC channel, 

So if only want same layout all time, can set it in GUI to "Using FC OSD_SW"

Otherwise, maybe try changing the OSD ch value just to see.

![image](https://user-images.githubusercontent.com/11336532/27176925-7a0ca1e0-51bc-11e7-8002-3dc86fe772b4.png)

**Comment by Markuzzzz** [comment]
Tried using different channels but still the same.. thing is I don't want screen switching but it always does on acro/level switch on aux port.

**Comment by ShikOfTheRa** [comment]
Had a look at code this morning and kiss does send mode control. There are two layouts associated with it.

So in brief, easiest way is to set all screen layouts to be the same. 

Change all layouts to be same as per pic (if three show, change all three)
![image](https://user-images.githubusercontent.com/11336532/27528970-ab0443de-5a4a-11e7-9c3e-94fcd449598d.png)
