### ISSUE TITLE
charset problem, osd on apm 2.6

### ISSUE THREAD

**Issue by turborocket** [ShikOfTheRa/scarab-osd#435]
Hi all,

i have 2 micro minimosd, both with 1.7 fw and bth with same config.

But 1 of those 2 has not clear on screen character.

![20170617_160514](https://user-images.githubusercontent.com/22917959/27261364-e3716dc8-5441-11e7-92ab-ad151ea38ad3.jpg)
![20170617_160527](https://user-images.githubusercontent.com/22917959/27261365-e37539c6-5441-11e7-868b-bf0934403039.jpg)

as you can see in the picture, the hud is customized, but the character are not clear, specialy when the video out is on.

in the photos, i was using an lcd display with a external vrx, but the same problem is on my goggles.
There is a picture of wiring
![20170617_160641](https://user-images.githubusercontent.com/22917959/27261415-b5c6798a-5442-11e7-91c3-6b5f14c3f0e4.jpg)

some advice?

**Comment by ShikOfTheRa** [comment]
There was a bug with one of the GUI versions which created an effect just like that.
I think to resolve, if you try reload fonts with latest it should be OK.

Another option is to use font uploader from utilities in flasher

**Comment by ShikOfTheRa** [comment]
Any luck?

**Comment by turborocket** [comment]
hello there! thx for the tip, i didnt tryed yet becouse im full of work in the last days!

i hope my son will sleep not too late tonight, so i can try it ;)

what are you suggesting me? i used the last 1.7 gui (payed), and what is the font uploader rom utilities in flasher?

**Comment by ShikOfTheRa** [comment]
You can use fontloader rom - or the font uploader button in GUI. Hopefully it will work. There was a definite issue with GUI. It should have updated automatically in background now. Please try again with 1.7.1.5

![image](https://user-images.githubusercontent.com/11336532/27827416-1219999c-60af-11e7-8afe-2e838a68ddc8.png)

**Comment by turborocket** [comment]
Hello,

i solved the problem by upload button on the 1.7.1.5 GUI

Thx a lot for the support!

2017-07-04 12:51 GMT+02:00 ShikOfTheRa <notifications@github.com>:
