### ISSUE TITLE
PX4 Compatibility  

### ISSUE THREAD

**Issue by 4cellOstrich** [ShikOfTheRa/scarab-osd#436]
Hi all,

I have been working for awhile on a fully compatible osd using minimosd hardware with px4 pixhawk fc's. I, unfortunately, have made very little progress. The issue lies in that the flight mode architecture is vastly different between the supported apm and unsupported px4, as well as some other data loss that I have not found the source of it yet, if anyone has a method that has fixed this, I would be extremely grateful! I really am an incompetent programmer, so I probably have overlooked some things.

Thank you!

**Comment by ShikOfTheRa** [comment]
I haven't used PX4 so can't help you unfortunately. I take it that it doesn't use mavlink? Are there any links that describe the protocol. 
Is this to add to MWOSD - more to create your own?

**Comment by 4cellOstrich** [comment]
Well it does use mavlink, however the structure is somewhat different, attitude data is conferred, but flightmodes, satellites, all that jazz is lost. And yes, ideally my goal is to make a compatible firmware. I can send you to the night-ghost minimosd repository where I tried, with no luck, to accomplish the same goal.

**Comment by ShikOfTheRa** [comment]
Hi - do you have a tlog of px4 serial data?

**Comment by 4cellOstrich** [comment]
Unfortunately I do not.

**Comment by ShikOfTheRa** [comment]
Hi - I started to look. At first glance see two areas
1 RC Channels / RSSI use different structure - I have added this in ready to test
2 Flight Modes - this looks to be different. Not quite clear tom me if its an issue or not.

The rest of the info - GPS etc. all looks normal - as long as its sent it should be displayed.

https://github.com/ShikOfTheRa/scarab-osd/tree/PX4

**Comment by ShikOfTheRa** [comment]
@4cellOstrich I have now added support for the different PX4 modes.
Just needs testing now to see what works / doesn't

**Comment by 4cellOstrich** [comment]
Amazing! Ill test ASAP!

**Comment by 4cellOstrich** [comment]
Worked like a charm! Many, many, thanks!

**Comment by ShikOfTheRa** [comment]
OK - pleasantly surprised. Let me know if anything is not working correctly

**Comment by 4cellOstrich** [comment]
so i guess there is one thing, even though the features seem to work perfectly, it has no longer interfaces with the configurator, which is so far the only issue i can see.

**Comment by 4cellOstrich** [comment]
also, the artificial horizion movement is inverted on the pitch axis

**Comment by ShikOfTheRa** [comment]
I had two others on APM to say pitch reversed so I have just amended. Surprised hasn't come up more often.

All updates are now in main repository. PX4 test branch removed.

For configurator - its working OK for me - have you set baud rate to match OSD - 56k default for PX4 ?

**Comment by 4cellOstrich** [comment]
OK yeah i had the baud rate wrong LOL

**Comment by ShikOfTheRa** [comment]
Good guess - Only because I do it all the time!!!

**Comment by 4cellOstrich** [comment]
This will sound asinine but in the new master release what hex file is the PX4 compatible one?

**Comment by 4cellOstrich** [comment]
and is it available on the config tool auto download?

**Comment by 4cellOstrich** [comment]
nvm! it works! if there are any more issues, ill be sure to let you know! Thank you so much man!

**Comment by ShikOfTheRa** [comment]
Hex files not there yet for download so only by using Arduino at momnet. I'll be working on a way to get test releases out quicker or direct from GUI config.
