### ISSUE TITLE
Show_Total_Distance

### ISSUE THREAD

**Issue by Schalonsus** [ShikOfTheRa/scarab-osd#437]
http://fpvlab.com/forums/showthread.php?34250-MWOSD-for-BETAFLIGHT-CLEANFLIGHT-RACEFLIGHT-PIXHAWK-KISS-DRONIN-INAV-and-others&p=829684&viewfull=1#post829684

would be great if added to master branch

**Comment by ShikOfTheRa** [comment]
Yes - will add shortly. Thanks for reminder..

**Comment by Schalonsus** [comment]
Thanks for adding
