### ISSUE TITLE
"Sketch too big" Arduino with Arduino pro or pro mini

### ISSUE THREAD

**Issue by mawright89** [ShikOfTheRa/scarab-osd#439]
I cant compile the sketch for any of the versions of MWOSD in arduino 1.8.2 with arduino pro or pro mini selected. I always get a failure that the sketch is too large.

Im trying to flash an onboard OSD on an emax Skyline32 OSD advanced which i believe needs the MinimOSD settings in MWOSD but i could be wrong so advice on that would be good too.

any help apreciated.

edit: the error code from arduino
Arduino: 1.8.3 (Windows 10), Board: "Arduino Pro or Pro Mini, ATmega168 (5V, 16 MHz)"

Sketch uses 25304 bytes (176%) of program storage space. Maximum is 14336 bytes.
Global variables use 1552 bytes (151%) of dynamic memory, leaving -528 bytes for local variables. Maximum is 1024 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Arduino Pro or Pro Mini.

**Comment by ShikOfTheRa** [comment]
You have wrong board selected. Not 168.   It's 328 which has double memory :)

**Comment by mawright89** [comment]
Haha omg what a bell end I am.. Thanks, appreciate the help. Can't believe I missed that.

**Comment by mawright89** [comment]
So now another issue... compiled correctly however.... tries to upload data however the light on the FDTI board blinks for around 5 mins then I get the error below. "an error occoured while uploading the sketch."

Arduino: 1.8.3 (Windows 10), Board: "Arduino Pro or Pro Mini, ATmega328 (5V, 16 MHz)"

Sketch uses 23332 bytes (75%) of program storage space. Maximum is 30720 bytes.
Global variables use 1895 bytes (92%) of dynamic memory, leaving 153 bytes for local variables. Maximum is 2048 bytes.
Low memory available, stability problems may occur.
An error occurred while uploading the sketch

**Comment by ShikOfTheRa** [comment]
Coulb many reaosns for thsi.
I'd start with 
1 correct com ports selected
2 is cabling correct between FTDI and OSD (is tehre is any cable...) must be 6 pins and correct rx>tx
3 google!

**Comment by mawright89** [comment]
ahh, right my FTDI cable only has 4 ports, 5V, GND TX and RX. What FTDI adapter would you recomend?

Many thanks for the help with this. I really appreciate it.

**Comment by ShikOfTheRa** [comment]
Thanks for update
