### ISSUE TITLE
Cannot increment values with left or right click reliably - MWOSD R1.3 SP2

### ISSUE THREAD

**Issue by chrisinvb** [ShikOfTheRa/scarab-osd#44]
With MWOSD R1.3 SP2, every timeI right click or left click to increment or decrement values, the interface seems to randomly respond.  I am using the 32-bit pre-compiled version MWOSD R1.3 SP2 on Windows 7.

Here is a link to a video on YouTube demonstrating the issue:

http://youtu.be/5WaYdU6VEEM

**Comment by ShikOfTheRa** [comment]
FAQ #17 - gets everyone!!! Weird operation and can't change it.....

17 I can't enter values into the GUI
Click onto the box and drag up / down. Obvious eh ?!
