### ISSUE TITLE
Display of sonar sensor

### ISSUE THREAD

**Issue by monterosa123** [ShikOfTheRa/scarab-osd#441]
Display the altitude measured by the sonar sensor in addition to the GPS and baro altitude.

**Comment by ShikOfTheRa** [comment]
Which FC?

**Comment by monterosa123** [comment]
SPRacingF3

**Comment by ShikOfTheRa** [comment]
Sorry which firmware

**Comment by monterosa123** [comment]
I'm using iNAV.

**Comment by ShikOfTheRa** [comment]
I have had a look - it is not in current standard commands so would need to add those in for exact sonar
I have added to the wishlist, but I don't have any time to implement this at present.

https://github.com/ShikOfTheRa/scarab-osd/wiki/Features-future-roadmap

I will close this as its logged in the request list. feeel free to ad any comments - they will still be read / viewed as get notifications for closed items too.
