### ISSUE TITLE
Add PIDs overlay

### ISSUE THREAD

**Issue by oyvinla** [ShikOfTheRa/scarab-osd#444]
I'm not sure if this has been asked before, but is it possible to add the abillity to turn on/off PID values to show on the screen while flying like you can in the Betaflight OSD? This would be helpful when tuning the quad in-flight with aux switches.

**Comment by ShikOfTheRa** [comment]
yes - this is currently in the request list:
https://github.com/ShikOfTheRa/scarab-osd/wiki/Features-future-roadmap

**Comment by ShikOfTheRa** [comment]
Am closing this as it is in the development request queue. I suspect in reality this will not be completed as many have migrated to onboard OSD for betaflight
