### ISSUE TITLE
Diagram MicroOSD v2.3

### ISSUE THREAD

**Issue by lukas12p** [ShikOfTheRa/scarab-osd#445]
Can You upload a diagram of MicroOSD v2.3 ?

**Comment by ShikOfTheRa** [comment]
That is produced by Airbot. I don't think it is released by them

**Comment by ShikOfTheRa** [comment]
@lukas12p
I can only provide this from google:
https://github.com/ShikOfTheRa/scarab-osd/blob/master/OTHER/DOCUMENTATION/DIAGRAMS/MINIM%20schematic.png
