### ISSUE TITLE
piggy v2 passthrough not working

### ISSUE THREAD

**Issue by spiffy59** [ShikOfTheRa/scarab-osd#446]
Having issues connecting.  Got waiting for OSD.  And Another Task In Process.  I am able to access OSD through video and controler but not directly with mwosd configurator.

**Comment by ShikOfTheRa** [comment]
I have no experience with passthrough unfortunately. 
An updated GUI will be released in a few weeks which introduces direct support support for passthrough.
Another task in progress usually means something is locke dup and have to reset GUI - or soemthing else is connected to com port on FC

**Comment by error414** [comment]
Did you read https://github.com/ShikOfTheRa/scarab-osd/issues/425 ?

**Comment by spiffy59** [comment]
No but I will thanks
