### ISSUE TITLE
Betaflight3.1 no data on MW 1.7.2

### ISSUE THREAD

**Issue by 4cellOstrich** [ShikOfTheRa/scarab-osd#448]
Hate to bother again, but,

I just updated my Kombini from BF 3.0 to 3.1, as well as my sp3 Vtx/OSD from mystery 1.6 to BF MW 1.7.2, however there is no data anywhere, all zeros. After looking into it I found that there was the issue with MSP, but that was addressed in this firmware so I am a little lost. I flashed from Arduino, tried to use LTM instead of msp, but just no luck anywhere. still the same stupid 0v 0%rssi and 0A staring me in the face. 

Sorry to bother again!

**Comment by ShikOfTheRa** [comment]
is MSP enabled at correct speed on correct port?  I have had no other reports

**Comment by 4cellOstrich** [comment]
Uart1 at 115000?

**Comment by 4cellOstrich** [comment]
i am about 90% sure that the port that im connected to is uart 1

**Comment by ShikOfTheRa** [comment]
OK as long as GUI not plugged in at same time. Will have to unlpug OSD each time want to use GUI.
I assume both tx and rx lines are connected

**Comment by ShikOfTheRa** [comment]
Enable hem all and see what happens!

**Comment by 4cellOstrich** [comment]
no the tx is unplugged from usb when its powered, i guess ill do that and see what happens!

**Comment by 4cellOstrich** [comment]
well i enabled them all and still nothing. This board was definitely working before so it has to be software...

**Comment by ShikOfTheRa** [comment]
I can test in a couple of days.

**Comment by 4cellOstrich** [comment]
awesome, ill keep you posted if anything changes

**Comment by ShikOfTheRa** [comment]
I just connect up betaflight 3.1 and 3.2 to MWOSD 1.7.2 and at least some of the functionality works.
I have no RC available to test further:, but the following at least work OK
Artificial horizon
Baro 
main voltage
rssi

**Comment by 4cellOstrich** [comment]
Nuts. What was fc/osd combo?

**Comment by ShikOfTheRa** [comment]
FC is a RMRC dodo clone and the osd is a stock minim.

**Comment by 4cellOstrich** [comment]
damn, ill try again, but im pretty sure its not a hardware issue bc its on 2 quads, do you have any special port setup?

**Comment by ShikOfTheRa** [comment]
Nope. Just a default setup then enable MSP on port and ensure its at correct baud rate

**Comment by 4cellOstrich** [comment]
which is 115000?

**Comment by 4cellOstrich** [comment]
i just dont get  it, it doesnt recognise arming either

**Comment by 4cellOstrich** [comment]
did you just flash the osd with betaflight MWosd and it worked? using the configurator?

**Comment by ShikOfTheRa** [comment]
Yep. Osd - betaflight minim 1.7.2 from configurator 
For FC I uploaded latest hex from releases. Think it was 3.2 rc x

**Comment by 4cellOstrich** [comment]
i guess ill go to 3.2 and try it? ive heard good things about it.

**Comment by 4cellOstrich** [comment]
actually im seeing that BF 3.1 in general was pretty weird on a lot of things so i hope 3.2 will be stable

**Comment by 4cellOstrich** [comment]
yeah switching to 3.2 fixed it, so, who knows!

**Comment by ShikOfTheRa** [comment]
Thanks for feedback. Brill
