### ISSUE TITLE
Chrome configurator will not connect

### ISSUE THREAD

**Issue by adamzimnyy** [ShikOfTheRa/scarab-osd#450]
Hello. 

I flashed the 1.7 version onto micro minimosd and was trying to connect using chrome app, but nothing happens after I click Connect. The log just shows "Connecting" and nothing else happens. 
I downloaded everything I use today, so I believe the version should be correct.

**Comment by ShikOfTheRa** [comment]
Are you using correct baud rate? 115k for MSP systems like xxxflight and 56k for APM/PX4

Also - try changing baud rate to a different value then resetting it back.

**Comment by zsoltm** [comment]
Same here.... Win10 / Chrome. If I flash 1.6 and use the old java client, it works. Other chrome apps, like Betaflight could connect to a FC on the same PC.

**Comment by yds** [comment]
@ShikOfTheRa 
> try changing baud rate to a different value then resetting it back.

That worked! Thanks for the tip. I've been having the same problem with [R1.7.2.2 Test Release](https://github.com/ShikOfTheRa/scarab-osd/releases/tag/1.7.2.2).

**Comment by adamzimnyy** [comment]
I tried changing baudrates, but still can't connect. Anything else I can try?

**Comment by ShikOfTheRa** [comment]
If you use pc and send email to spam<at>flypix.co.uk I can send you a PC client to try instead.

It is surprising that it flashes OK, but unable to connect for normal configuration... very starnge

**Comment by slawekgajzner** [comment]
Hello.
I also can not connect to version 1.7.

If I use the configurator from 1.6 it connects but says that the configurator is not up to this version.

**Comment by flexbex** [comment]
What worked for me was touching serial port and baud rate selector one time. Because values are shown but not selected internaly.

**Comment by slawekgajzner** [comment]
Thanks, it works.

**Comment by asdiasx** [comment]
Had this problem and solved chanding baudrate for the com port in windows... it was 9600 by default...

**Comment by ShikOfTheRa** [comment]
This is now included in latest GUI configurator
