### ISSUE TITLE
my OSD is gone

### ISSUE THREAD

**Issue by MintJDM** [ShikOfTheRa/scarab-osd#451]
when i was using the chrome extension i selected the option "default" and EVERYTHING is now gone in my goggles and when i try to get it back nothing happens

https://gyazo.com/a6eb1a4cfbb02755d393c2be6ff153a7

**Comment by ShikOfTheRa** [comment]
Wiki FAQ #2. Proabaly pal/ntsc setting

https://github.com/ShikOfTheRa/scarab-osd/wiki/FAQ

**Comment by MintJDM** [comment]
Thanks for the help. You were right.

**Comment by ShikOfTheRa** [comment]
Thanks for feedback!
