### ISSUE TITLE
Voltage with KISSFC

### ISSUE THREAD

**Issue by djecom** [ShikOfTheRa/scarab-osd#453]
I'm using mwosd 3.7 with a KISSFC and I read the voltage from the Kiss.
But I have a difference between the real voltage and the OSD one (around 0.6V). 
Using the 'voltage calibration' on the OSD don't work (because I use the FC volage?)

Is there a solution for me ?

**Comment by ShikOfTheRa** [comment]
Can you adjust on Kiss FC? The OSD only displays what is being sent.... 
Other option is to connect to thet vbat input and use OSD on board voltage monitoring
