### ISSUE TITLE
NAZA M V2 Support?

### ISSUE THREAD

**Issue by UebertreibeR** [ShikOfTheRa/scarab-osd#459]
Hi Guys,

I am wondering how well the support for NAZA M V2 is with the latest MWOSD. Can I get RSSI, Battery Voltage, Height & Distance readings to work just by bridging the green wire from DJIs compass cable?

**Comment by ShikOfTheRa** [comment]
Should be fine.

I have used myself but only a few times before I sold DJI gear.
RSSI and bat are connncted direct to OSD. Doesn't get that from the NAZA puk
Also don't get AHI pitch / roll.
