### ISSUE TITLE
MWOSD v1.7.1.9 (windows client) Button Write not Working

### ISSUE THREAD

**Issue by vitorzone** [ShikOfTheRa/scarab-osd#460]
I have flashed the OSD, the button Read works but the Button Write it's always inactive.

**Comment by ShikOfTheRa** [comment]
Hi - I have just installed it and it is there for me.. Did it register OK?

**Comment by vitorzone** [comment]
Hi. Register? I bought the configurator by "https://www.virtualpilot.co.uk". How can I get the code to register? Thanks.

**Comment by ShikOfTheRa** [comment]
You should have received an activation code. Drop an email to them requesting resend of key. Will need your email address it was purchased with.

**Comment by vitorzone** [comment]
I already ask for the activation code to them. Let's wait now. Thanks.

**Comment by vitorzone** [comment]
I did not have that registration information, when I bought the configurator. It's pefect now. Thanks.

**Comment by ShikOfTheRa** [comment]
OK - thanks for feedback!
