### ISSUE TITLE
Voltage from FC shows correctly, will not trigger alarms though.

### ISSUE THREAD

**Issue by benipk** [ShikOfTheRa/scarab-osd#464]
When "Use FC main voltage is checked" the OSD will show the correct voltage. However it will not trigger any low voltage text alarms on the OSD, I'm unsure whether this is an issue or simply an unimplemented feature.

**Comment by ShikOfTheRa** [comment]
Shouldn't make any difference. I will test today...

**Comment by ShikOfTheRa** [comment]
Hello. I just tried 1.7.2 and it seemed to work. FC at 16.1v, set alarm to 160 and voltage flashes. Also get text alarm. 
I assume text alarm is enabled? Needs to be enabled in screen layout and also in menu/gui
