### ISSUE TITLE
Fonts not loaded 1.7.1.9

### ISSUE THREAD

**Issue by andrew00077** [ShikOfTheRa/scarab-osd#468]
Hello,

I loaded the bold fonts with the Chrome app (FONT->Change->default_bold.mcm->Upload) but when I disconnect and reconnect again, the fonts are not Bold (inside the configurator I still have the normal fonts and not the bold ones).
How to solve the problem?
Thanks!

**Comment by ShikOfTheRa** [comment]
FAQ #14 
https://github.com/ShikOfTheRa/scarab-osd/wiki/FAQ
