### ISSUE TITLE
write to OSD not working

### ISSUE THREAD

**Issue by vannoz** [ShikOfTheRa/scarab-osd#475]
hello I purchased the PC version of GUI. the Write pushbutton is litegrey...and seems not writing to OSD.
what I miss?
thanks

**Comment by ShikOfTheRa** [comment]
click register button and enter the activation key

**Comment by vannoz** [comment]
Ops... Thanks!!!!

Il 09/feb/2018 20:01, "ShikOfTheRa" <notifications@github.com> ha scritto:
