### ISSUE TITLE
add support for DJI N3 autopilot

### ISSUE THREAD

**Issue by sincoder** [ShikOfTheRa/scarab-osd#485]
As i know this fly control send info to CAN bus

**Comment by ShikOfTheRa** [comment]
Unfortunately the standard minim and clone hardware will not support this.

**Comment by sincoder** [comment]
use a extra CAN-to-TTL adapter?

**Comment by ShikOfTheRa** [comment]
Hi - I have had a look and unfortunately have no plans to do this. I think would need another board to handle the high speed of canbus and then pass to mwosd in mavlink or MSP format.
Its quite achievable - I see pawelsky on rcgroups has produced library to implement. Needs time and equipment to do it. Probably easier to buy DJI OSD

**Comment by sincoder** [comment]
the DJI iOSD does not support battery current meter, it is a very Important feature. Many fly controllers have onboard OSD chip and a STM32 chip ,so we can just make the Fly controller board as OSD board

**Comment by ShikOfTheRa** [comment]
If someone wants to do the code and add N3 support I would be happy for it to be merged into MWOSD

If it was me I would use 2 OSD - DJI for main items / modes and add a second minimosd to overlay current? I know others have done that using mwosd

**Comment by sincoder** [comment]
seems a good solution
