### ISSUE TITLE
Enable/disable Blackbox logging via inscreen menu?

### ISSUE THREAD

**Issue by NL-Splinter** [ShikOfTheRa/scarab-osd#49]
Would it be possible to enable/disable blackbox logging via an option in the inscreen OSD menu?

**Comment by ShikOfTheRa** [comment]
I have no idea even what that is ?

**Comment by tracernz** [comment]
Cleanflight has a module which can record parameters inflight for later analysis. See https://github.com/cleanflight/cleanflight/blob/master/docs/Blackbox.md. They don't have an MSP command to enable/disable Blackbox recording so this currently isn't possible (https://github.com/cleanflight/cleanflight/blob/master/src/main/io/serial_msp.c).

**Comment by ShikOfTheRa** [comment]
Oh actually I recall seeing this. The data overlay on a video was simply awesome.

No MSP = definitely no to ass. Sorry.
