### ISSUE TITLE
Incorrect Miles Long Distance Calculation

### ISSUE THREAD

**Issue by trailx** [ShikOfTheRa/scarab-osd#505]
`ifdef LONG_RANGE_DISPLAY`
`    if (d2f>9999){`
`    if(Settings[S_UNITSYSTEM]){`
`      tmp = ((d2f) + (d2f%5280))/528;`
`    }`
`    else{`
`      tmp = d2f/100;`
`    }`
`    itoa(tmp, screenBuffer+units, 10);`
`    uint8_t xx = FindNull();`
`    screenBuffer[xx]=screenBuffer[xx-1];`
`    screenBuffer[xx-1] = DECIMAL;`
`    xx++;`
`    screenBuffer[xx] = 0;`
`    type = (type==2) ? type=6 : type=4 ; //          `
`  }`

Miles is being calculated incorrectly in the screen.ino file, at line 2512.

` tmp = ((d2f) + (d2f%5280))/528;`

Should be:

` tmp = (((d2f)/528)+.5);`

This video explains it with more detail:

https://www.youtube.com/watch?v=_SIzaa_hUdc

More discussion here: http://fpvlab.com/forums/showthread.php?34250-MWOSD-for-BETAFLIGHT-CLEANFLIGHT-RACEFLIGHT-PIXHAWK-KISS-DRONIN-INAV-and-others&p=846018&viewfull=1#post846018

Thanks!

**Comment by ShikOfTheRa** [comment]
Great job - thanks. Will get on to this today

**Comment by ShikOfTheRa** [comment]
OK - confirmed bug. 
Have submitted an update to main repository for testing.

Added rounding improvements as per your 0.5 suggestion. It never bothered me and always wondered when someone would pick it up!

**Comment by trailx** [comment]
Thanks for taking a look!  Now I need to figure out how to flash my OSD.

**Comment by ShikOfTheRa** [comment]
I can produce a hex for you if it’s easier? Inav fixedwing?

**Comment by trailx** [comment]
That would be awesome!  I'll be out flying wednesday and can test then if you can make that happen!  I have this inav fixed wing OSD: http://www.carbonbird.com/products/inav-osd-for-air3-airhero32  Not sure if that makes a difference or not.

So, all I have to do is just upload using the flash button on the chrome MWOSD app, and load the hex file from disk?  I assume the osd settings will be unchanged before/after - or do I need to export/import?  (Thanks! - I try not to update firmware when things are working, so I'm always a little hesitant when I do)

**Comment by ShikOfTheRa** [comment]
OK. Easier solution:
No change to settings...
Tick "Show test releases" in GUI
Should see 1.8.0.1

**Comment by ShikOfTheRa** [comment]
confirmed resolved in main resository. Full release available shortly.
