### ISSUE TITLE
Can't write config to OSD from GUI. MSP simulation is working.

### ISSUE THREAD

**Issue by mazsola76** [ShikOfTheRa/scarab-osd#507]
MWOSD 1.8.0.0 (standalone PC version)
FW. "Minim", loaded online
"Write" button is inactive despite many setting changes.
MSP simulation is working, on the other hand.
Am I missing something?

BR,
Zsolt

**Comment by ShikOfTheRa** [comment]
Hi - have you registered? button under connect?

**Comment by mazsola76** [comment]
OK, solved!
Maybe it would be a good idea to make a popup window for unregistered users to explain THIS software is not registered and what it means (not to pull out their hairs what's happening :)
Great software, the simulator is an awesome idea, but the buttons must be ironed out a bit  - for me they are shifting all over the main window, and are responsive mainly at their lower edges :(  - if at all.
Thanks and best regards,
Zsolt

**Comment by mazsola76** [comment]
One issue remains:
Loading a previous config from a .json file is possible on the virtual OSD, but the "write" is failing.
Modifying as many parameters as you wish on the virtual OSD and uploading them works fine!
