### ISSUE TITLE
Voltage issues

### ISSUE THREAD

**Issue by sevrugin** [ShikOfTheRa/scarab-osd#521]
Hardware:
APM 2.8
microminimosd connected to the FC telemetry
MWOSD 1.8

FC is powered by 3s or 4s battery
OSD is powered by custom 5v adapter

Issues: 
- Main voltage is show 3.2v with alarm 
  souce: FC voltage / autodetect cell count and cell alarm / autodetect cell alarm 3.4
- Video voltage is show 0v (I tried to switch between BAT1 and BAT2 pin on the OSD board)

If I switch voltage source to the "DC source" then "Video voltage" is show correct data but main voltage is 0v

So question is - can I choose "FC source" for the main voltage and "DC source" for the video voltage?

PS: On the 1.7 firmware it worked correctly

**Comment by ShikOfTheRa** [comment]
Hi - I have amended - can test this by using firmware flasher. Select "show test releases" and pick 1.8.1.5 or later.

I am not sure about the first point - I see correct operation there. 
Might be worth setting defaults from gui after upgrade and re-connecting

**Comment by sevrugin** [comment]
Great! I'll test in the evening

**Comment by sevrugin** [comment]
Great work! 
Thanks for your fix! Now everything work as expected! 

Another question. 
Is there a way to add "m/s" to the Units of Measure? 
I'd like to see speed (AS and GS) and variometr on the m/s

**Comment by ShikOfTheRa** [comment]
Yes - this is possible. I am happy to add this to the development list. It is minor so can do soon.

But... - it will be a custom install using arduino to edit/upload - not available in GUI as it is rarely used and unfortunately I do not have the memory to be able to support all features. I wish I could!

If you are happy wit this approach I do it for you.

**Comment by ShikOfTheRa** [comment]
Oh - and thanks for testing and confirmation feedback!

**Comment by sevrugin** [comment]
It would be great! Thanks!
No problem to use Arduino

**Comment by ShikOfTheRa** [comment]
Added the m/s request into development road map. I plan to do this soon.

Think the issue can be closed
