### ISSUE TITLE
Long lines breaking arduino IDE

### ISSUE THREAD

**Issue by ledvinap** [ShikOfTheRa/scarab-osd#528]
Lines  in font?.h are too long, probably breaking Arduino IDE function signature generation. 
Build then fails with 'checkEEPROM' was not declared in this scope.

Splitting the line roughly in half will fix the problem.

(edit: set LOADFONT_DEFAULT to trigger this)

**Comment by ShikOfTheRa** [comment]
Ah yes - had this before. Correct - I had to split the lines. I updated fonts and forgot....
If works in platformio :)

i'll update....

In GUI flasher - utilities, fonts there are precompiled ones

**Comment by ShikOfTheRa** [comment]
Also to add - I think it depends upon Arduino / compiler version
1.6.5 seems to work OK. Vagualy recall this too.

**Comment by ledvinap** [comment]
I tried 1.6.something and 1.8.5, both fail
It's just one of many annoying Arduino IDE bugs/features ...

**Comment by ShikOfTheRa** [comment]
I've updated in main repository. Thanks again for pointing out.

It worked for me with single line in 1.6.5 and also platformio - but I know I definitely had same issue.

**Comment by ShikOfTheRa** [comment]
Ok think this cam be closed- please re-open if not resolved.

I'll try to remember to split files in future...
