### ISSUE TITLE
Motor and Servo Problem

### ISSUE THREAD

**Issue by Ary-Oks** [ShikOfTheRa/scarab-osd#539]
Dear All Friend,

I have some problem setup cc3d on glider plane.

If arming servo and motor can not spin. I have setup for extra safety arming value set is Off for test only. but motor and servo not spin.

I reflashing cc3d board. i have realease gps from.board and problem is clear. motor and servo working well, but if i have replace gps on board, the servo and motor still problem.

Please help

**Comment by error414** [comment]
I think that some FWs (inav, cleanflight) have pre-arm checkm GPS must has 3D fix. And it seems that it is inav, cleanflight, etc.. problem,. not MWOSD problem.
