### ISSUE TITLE
Release r1.9 issue tracker

### ISSUE THREAD

**Issue by ShikOfTheRa** [ShikOfTheRa/scarab-osd#543]
Please report any issues identified in this tracker.

OSD:
Completed in OSD 1.9.0.2 - Users running iNAV and no GPS - low sats warning on permanently
Completed in OSD 1.9.0.3 - Lon indicator incorrect
Completed in OSD 1.9.0.4 - iNAV FC access settings page missing
Completed in OSD 1.9.0.6 -Altitude always displays meters instead of feet 

GUI:
Completed in GUI 1.9.0.1 - Unable to write after moving some screen elements
Completed in GUI 1.9.0.2 - RSSI source channel 14 missing
Completed in GUI 1.9.0.2 - Reports Ardupilot FC instead of APM
Completed in GUI 1.9.0.2 - Reports FlightOne FC
Completed in GUI 1.9.0.2 - Reintroduce glidescope for copter
Completed in GUI 1.9.0.2 - Shift characters one column to right.

Outstanding - amend reported variant of APM to Ardupilot

Enhancement requests:
Completed in 1.9.0.1 - Request to add AUTOTRIM & AUTOTUNE indicators
Completed in 1.9.0.2 - Request for improved AHI support - wider range and inverted accuracy
Completed in 1.9.0.5 - Request for FlightOne support
Request to show iNAV arming error status reasons

**Comment by dwoolworth** [comment]
I'm running Arduplane v3.9.2 and using MWOSD 1.9 on MinimOSD unit.  Seems although I've selected "Imperial" as the units of measure, while MPH and Feet/Miles are working properly, the Altitude is still in meters, although it shows "ft" after the reading.

**Comment by ShikOfTheRa** [comment]
@dwoolworth - bug confirmed. Thanks for reporting. My erorr - bug introduced after significant code changes to reduce memory for new features. Annoyed I missed that. . It should be fixed in 1.9.0.6 onwards - currently available if select "show test releases".

**Comment by dwoolworth** [comment]
@ShikOfTheRa - It's all good!  Thank you for such an awesome product and pretty much the best OSD available!

**Comment by ShikOfTheRa** [comment]
R1.9.1.1 is release with all reported bugs hopefully addressed. 

Closing this release tracker
