### ISSUE TITLE
MinimOSD not uploads fonts.

### ISSUE THREAD

**Issue by gppsoft** [ShikOfTheRa/scarab-osd#545]
I am upload font from MWOSD Configurator, but nothing chages. Why? I use pixhawk with ardupilot firmwire.

**Comment by ShikOfTheRa** [comment]
FAQ #14 

14 I get garbage characters and / or font upload doesn't work.

Sounds like fonts need to be re-uploaded - but note:
**For some of the original minim boards, the output stage (max chip) MUST be powered when uploading font. How depends upon your board / configuration**
A programming voltage of 4.8v or higher is required.
Note some programmers have 3.3v/5v selection text swapped. Verify with a meter
Some stacked boards with USB connector also require vbat connected which powers the MAX chip and enables font upload
Programming with FC passthrough is not always successful.
