### ISSUE TITLE
CC3D NAZE32 PDB OSD can not flash v1.9

### ISSUE THREAD

**Issue by davidngrc** [ShikOfTheRa/scarab-osd#547]
Hi

Just bought your MWOSD v1.9 today
I have this CC3D NAZE32 PDB OSD board https://www.rcmoment.com/p-rm6588.html

I can't flash it via the MWOSD 1.9 configurator windows 64 bit version.
it always said timeout, I have try all different type of board in the menu, like miniosd microosd...
read the osd ok, but it alert the version does not suppoted.

I also try the Arduino IDE method mention here
https://www.youtube.com/watch?v=d-DPYlAVojA

I am using iNav with MSP on first UART
BTW the board came with MWOSD v1.6 free version, and the 1.6 free configurator is ok.

Please help
David

**Comment by ShikOfTheRa** [comment]
Hi

I have not seen one of those boards before.

1 – Try flashing without it being powered by anything else other than the USB
2 – disconnect the rx/tx lines from FC
3 – If unable to program using Arduiino method then it’s definitely not an issue for GUI

Some of boards can’t be programmed by GUI or Arduino – manufacturer made decision not to include the bootloader required to program over serial connection
