### ISSUE TITLE
Configurator key invalid

### ISSUE THREAD

**Issue by jacobwood27** [ShikOfTheRa/scarab-osd#551]
I get a 'Bad Key' error when pasting my key I purchased today into the Configurator v1.9.0.1 registration window.

**Comment by error414** [comment]
Hello Jacob,

I tried use your serial key and it works, I used win version, what OS do you use? And can you send me screenshot of error?   My email error414@error414.com

ShikOfTheRa (Gary) is on holiday. 

BTW: you can check here who I am https://github.com/ShikOfTheRa/scarab-osd/wiki/Credits
