### ISSUE TITLE
List of questions

### ISSUE THREAD

**Issue by liguo-git** [ShikOfTheRa/scarab-osd#564]
1、inav2.1.0 pid  dysregulation；
2、inav2.1.0  GPS height not displayed

SPRACINGF3   microminim.inav.multirotor.hex

**Comment by liguo-git** [comment]
![Want to add this feature](https://github.com/liguo-git/img/blob/master/inav.png)

**Comment by ShikOfTheRa** [comment]
Hi,
For 1 – do you mean to add PID display support?

For 2 - 
 
![image](https://user-images.githubusercontent.com/11336532/57527225-21d47000-7327-11e9-933e-456b4d9be66d.png)

**Comment by liguo-git** [comment]
For 2 is small house？

**Comment by ShikOfTheRa** [comment]
Hi, 

Below is screen with "Show both positions"
it is H instea dof house, but you can create your own icon if you prefer house.
 
![image](https://user-images.githubusercontent.com/11336532/57701040-08973080-7653-11e9-8bf3-db991c95c7a3.png)

**Comment by liguo-git** [comment]
oj8k， Thanks

**Comment by liguo-git** [comment]
Map mode display type
I tried
show home position show icon ok
No other
