### ISSUE TITLE
RSSI FlightOne problem

### ISSUE THREAD

**Issue by BlacScrap** [ShikOfTheRa/scarab-osd#566]
Hi, i have problem. RSSI not working in my MinimOSD.
I typed in console FlightOne - set telem_msp=4 and command "rssi" show normal value.
TX4 pad bridge to normal,
I set in my taranis rssi in 8 or 16 channel,
In MWOSD Configurator - RSSI tab set "RSSI Source" - RSSI from RC channel, "RSSI Channel" set 8 or 16.
RSSI stands still in 73%. 

I don't know why not working... Help me :(

**Comment by ShikOfTheRa** [comment]
Hi - installing debug will help see channels 1-8 to see if data is coming OK from the FC:
![image](https://user-images.githubusercontent.com/11336532/58165451-bae87c80-7c7f-11e9-838d-89dd6c02eac9.png)


Also, F1 is current set to use only 8 channels.. Will need to:
1 https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide
2 in config.h enable and amend to #define TX_CHANNELS 16

In not sure how to do this, let me know and I'll creat a build you can test / install.
If this works, I'll release anew version with 16 channels enabled as default.

**Comment by BlacScrap** [comment]
#define TX_CHANNELS 16 - it works!

Thank you so much! :)

**Comment by ShikOfTheRa** [comment]
Thanks for feedback. I'll enable permanently and make this available as precompiled release for flashing in next couple of days.
