### ISSUE TITLE
OSD disappears when armed

### ISSUE THREAD

**Issue by pumpkinheadnick** [ShikOfTheRa/scarab-osd#568]
Hello I am using the Lumenier LUX V2 flight controller and the DLUX OSD. I am using betaflight and all firmware is up to date. I have gotten everything on the flight controller to work and can arm and controller my copter. I have used the MWOSD software to flash the OSD. 

![OSD](https://user-images.githubusercontent.com/44915530/59369152-c45c8600-8d0d-11e9-9109-e064e532c97b.JPG)

My OSD is powered directly off of the PDB and there are no voltage dips when arming. My issue is that when I arm the copter all the data disappears.

I have found this post in the FAQ but can't get a resolution. 

"7 My OSD turns off in flight / after powering up motors?

Ensure you have a good ground                    
Use a big cap (e.g. 3300uf) on the 5v supply to the OSD
Enable #define MAXSTALLDETECT in config or upgrade if not listed as an option"

I know there is a good ground. 
I am not powering off 5V 
I don't know where you want me to type "#define MAXSTALLDETECT "

Please help

**Comment by ShikOfTheRa** [comment]
Do you have arming on a switch ? IF so - is it the same channel as in the layout tab? Maybe it is changing to a blank screen layout.
