### ISSUE TITLE
ver 1.9.1.1 strange characters minimosd pixhawk

### ISSUE THREAD

**Issue by 66nola66** [ShikOfTheRa/scarab-osd#569]
I am running ver 1.9.1.1 on minimosd and pixhawk. I am in correct telem port and everything is responding correctly but I have strange characters showing up for the altificial horiz. and the alt. and speed side bars(these look like padlock with a G in the middle). I am running BOLD fonts and I am powering both sides of the minim from the FC 5vdc. The artificial horiz. actually has random letters making up the bars and center marker. Any help would be greatly appreciated. Thanks!

**Comment by error414** [comment]
Hi 66nola66,

can you attach picture how it looks like? I tried find char which would looks like padlock wig G but without success. 

Did you try re-upload new font?

**Comment by 66nola66** [comment]
![IMG_20190623_133423](https://user-images.githubusercontent.com/52134427/59980505-96542d00-95bc-11e9-829f-b9391d4aae3e.jpg)
![IMG_20190623_133427](https://user-images.githubusercontent.com/52134427/59980506-96542d00-95bc-11e9-8909-df2915c34e0d.jpg)
![IMG_20190623_133501](https://user-images.githubusercontent.com/52134427/59980507-96542d00-95bc-11e9-96ed-4588637d2da4.jpg)
![IMG_20190623_133519](https://user-images.githubusercontent.com/52134427/59980508-96542d00-95bc-11e9-9952-fac19a72318c.jpg)

I havent tried to reload new font but will do that next. I did hear that when loading a file it needs to be done with both sides of the minim powered which I didnt do originally but have since done with similar results. Here are the PICs you requested. AND THANK YOU!!

**Comment by error414** [comment]
I am sure that load new font is the key :).

**Comment by 66nola66** [comment]
That did it!!!! THANK YOU!!! EXCELLENT SUPPORT!!!!
