### ISSUE TITLE
Cleanflight 1.9 RC TUNING labels are wrong

### ISSUE THREAD

**Issue by CrazyCoder** [ShikOfTheRa/scarab-osd#57]
Roll and Pitch rates are now separate, so all the parameters after ROLL PITCH RATE are off.

YAW RATE displays PITCH RATE.
TPA displays YAW RATE.
THROTTLE MID displays TPA
etc...

Also,

ROLL displays 0
PITCH displays TPA Breakpoint value.

Using master build as of today (69e1146dc925dd2ff3f8974476f0a7bff2e5e3e1).

**Comment by CrazyCoder** [comment]
This problem is a result of removing `CLEANFLIGHT` define and replacing it with `CLEANFLIGHT190`, `CLEANFLIGHT181` and `CLEANFLIGHT180`. The code in `GlobalVariables.h` still depends on `CLEANFLIGHT` define which no longer exists.

**Comment by ShikOfTheRa** [comment]
Yes - thank you for the feedback. Unfortunately I don't have a setup to test cleanflight so relaying entirely on community testing at the moment. Have made those changes

**Comment by ShikOfTheRa** [comment]
Hello - any chance to test beta download PRE1.5 is working OK ?

**Comment by CrazyCoder** [comment]
Should work, I've compiled it after a fix and it worked fine.

**Comment by ShikOfTheRa** [comment]
OK - thanks for quick reply!. See if I can get a few other testers to OK the cleanflight then post the latest compiled as full release.

**Comment by ShikOfTheRa** [comment]
OK no bad feedback so far from latest. Closing  :)

Thanks for assistance..!!
