### ISSUE TITLE
v1.9.1.3: REVERSE_AHI_ROLL wrongly implemented

### ISSUE THREAD

**Issue by Philippe-France** [ShikOfTheRa/scarab-osd#571]
hello

in screen.ino v1.9.1.3 there is this mistake

#if defined REVERSE_AHI_ROLL
   pitchAngle = -pitchAngle;   <== should be: rollAngle = -rollAngle;
#endif //REVERSE_AHI_ROLL

regards

**Comment by ShikOfTheRa** [comment]
Hi - thanks for pointing this out. I guess it has never been used!

It is now updated in master.
 Thanks again!

**Comment by ShikOfTheRa** [comment]
Available in test release 1.9.1.5

Will also be in next full release

Thanks again
