### ISSUE TITLE
Garbage fonts

### ISSUE THREAD

**Issue by Tofandel** [ShikOfTheRa/scarab-osd#598]
I'm having a garbage font issue on my OSD, I'm using MWOSD Configurator 1.9.1.1 on linux, flashing 1.9.1.4 -> minim -> ardupilot -> aero

![garbage](https://user-images.githubusercontent.com/6115458/77249247-083acf00-6c40-11ea-9112-5ad79d283de2.jpg)

I'm programming with a good 5v, I tried also powering the video chip when programming with 12v, I cleared the eeproom using the utilities and then programming the fonts as well with the utilities and reflashing again.

I also tried a lot of different combination of the previous things, none made a difference, I'm still seeing the exact same icons

My board looks like this
![IMG_20200322_131511](https://user-images.githubusercontent.com/6115458/77249378-fa397e00-6c40-11ea-9502-445734073174.jpg)
![IMG_20200322_131550__01](https://user-images.githubusercontent.com/6115458/77249581-708ab000-6c42-11ea-9ee8-22886412f0a8.jpg)

Any ideas?

**Comment by ShikOfTheRa** [comment]
Sounds like your doing everything correctly.

Definitely need 12v and gnd 
(as you have gnd jumper left unbridged) on the video stage of the board when uploading the fonts (not needed just for the firmware).
