### ISSUE TITLE
Can VTX power and/or Channel information be added?

### ISSUE THREAD

**Issue by sevet** [ShikOfTheRa/scarab-osd#602]
Can you please add VTX power and channel? they need to be separate options (I don't really use channel, just power, but many use  it)

**Comment by ShikOfTheRa** [comment]
I will have to think about approach for this. Something we can do within constraints of memory. 
Leave with me a couple of days

**Comment by ShikOfTheRa** [comment]
Hi, I have implemented this and uploaded to the master repository, but have no way to test. 

When using kiss, the GUI "gimbal" field can be used to display VTX power and channel.
In config.h you can choose VTX, Power or both (default).
![image](https://user-images.githubusercontent.com/11336532/80603562-8309bd80-8a28-11ea-857f-79c048c7c960.png)
