### ISSUE TITLE
Is glidescope in the good way

### ISSUE THREAD

**Issue by Benoit3** [ShikOfTheRa/scarab-osd#617]
hello,

I thank you for the mwosd which is very easy to install and to use. I use it on a quadcopter X500 with arducopter.

One question and possibly one issue. I've been very surprised with the glidescope behaviour which moves in the wrong way if I compare it to the standard glideslope indicator of any real aircraft :
- if the aircraft is above the descent flight path, the diamond is in the lower part of the scale
- if the aircraft is below the flight path, the diamond is in the upper part of the scale
In fact on an aircraft glideslope, the diamond symbolize the flight path, and the aircraft is symbolysed by the mid scale mark.

So is the mwosd glidescope a wanted behaviour or a (small) mistake ?

If correction is needed, I can participate to correction and test.
Regards,
Benoit
PS: I've another remark, normaly, on aircraft PFD, the glidescope scale is between the attitude indicator, and altitude tape. I can provide picture if needed

**Comment by ShikOfTheRa** [comment]
Hi - thank you for feedback and yes it was wanted behaviour. It was how described to me by the pilot requesting it originally a few years ago.
I am not sure - maybe there are different systems? It is inteersting no-one has commented before - or maybe it is not used much. I must admit I do not use it for landing aid. Maybe landing would be more consistent if I did :) 
It can be changed in code. Could add an option for user to select, but it would have to be a choice for a custom installation via config.h 

This is also true of ahi. I have seen both methods used one normal (to me) and other reversed. Reversed is popular in eastern countries. Also used by DJI too.  I hate it - seems so unnatural.

Yes please - link to picture or show yours. I t can be moved how you want. I set default position purely for balanced look.
