### ISSUE TITLE
Help garbage font of mwosd 1.9.2

### ISSUE THREAD

**Issue by abimaputra78** [ShikOfTheRa/scarab-osd#622]
Dear Shiki,

Presently, I used a paid version mwosd 1.9.2 for burning mwosd kiss gps osd firmware. With flasher feature in your mwosd, FTDI and minim micro osd like usuaI, tried several times... Eeprom clear,  re-flash, the osd font seemed... strange or there was some overlay of my old osd kiss firmware fonts and icon. How will the solution be? Pls assist and advice. I need to use mwosd for kiss gps. 

Pls assist how to set LQ Crossfire with rx channel 8=LQ. Will be ~ 80 warning, ~70 critical warning

Thanks 
Ditto.

**Comment by ShikOfTheRa** [comment]
Are you working following emails?

Support is from community here:
https://www.rcgroups.com/forums/showthread.php?3131701-MINIM-OSD-%C2%96-MWOSD-software-for-Ardupilot-iNAV-Betaflight-KISS-GPS-OSD-PX4


This site is intended for development issues.

**Comment by ShikOfTheRa** [comment]
Hi Ditto - will close this as we got you working
CH8 resolved for next release.
KISS Crossfire and GHOST  LQ. Added to tracker for development. No guarantees, but will try...
They are available as RSSI values now if Crossfire etc to output that as an RSSI channel
