### ISSUE TITLE
Feature request - load/save current screen layout

### ISSUE THREAD

**Issue by RMFPV** [ShikOfTheRa/scarab-osd#623]
Please add this option, or as an alternative just copy screen layout from any other screen.
Thank you!

**Comment by error414** [comment]
Good point, it will be in next release. 

![image](https://user-images.githubusercontent.com/1698092/98422893-47157c00-208d-11eb-83f2-cc46b9403911.png)

**Comment by ShikOfTheRa** [comment]
OK - I'll close a s done ready for next release
