### ISSUE TITLE
Some ideas for GUI improvement. 

### ISSUE THREAD

**Issue by RMFPV** [ShikOfTheRa/scarab-osd#624]
1. Font editor is brilliant. The only feature it's missing is moving the whole character inside the box. Sometimes it's necessary to change character position slightly.
2. It would be very helpful to store the current path separately for the settings file, telemetry player, and font directory.

**Comment by error414** [comment]
Hi,

1) good idea, I'm going to add it to next version https://www.youtube.com/watch?v=7RGpgz4JuXo
2) I will try look at that

**Comment by RMFPV** [comment]
Great! Thanks!
Video is private, though.

I would also suggest changing Aero in FW selection for something more common like Fixed Wing or Plane.

**Comment by error414** [comment]
I has fixed video.

It's auto generated text from https://github.com/ShikOfTheRa/scarab-osd/releases/tag/1.9.2.0 I can add "translation" but it's low priority change.

**Comment by ShikOfTheRa** [comment]
Agreed - plane is done ready for next release

**Comment by ShikOfTheRa** [comment]
OK - I'll close as done ready for next release
