### ISSUE TITLE
single cell average voltage

### ISSUE THREAD

**Issue by corrado-c** [ShikOfTheRa/scarab-osd#625]
Hello!!!
i am using microminim osd in different constructions,
the thing I miss most is having the ability to read the SINGLE CELL AVERAGE VOLTAGE.
I often use direct connect voltage, without FC, GPS osd, for RC CAR so to read voltage and speed.
but also in the other configurations I think it is very convenient because I often change the type of batteries.

Maybe it is me who am not good at setting this function in cofigurator. :)

I hope I got the right branch, I don't know which mwosd is referring to.

thanks !!

**Comment by corrado-c** [comment]
damn me ...
only now i saw that it can be done via arduino IDE ...
it took me a while to set it up but now it works.
if I understand correctly: VOLTAGE VIDEO becomes average cell voltage,
quite right?

**Comment by RMFPV** [comment]
yes

**Comment by ShikOfTheRa** [comment]
This is also available as an additional GUI configurable item from the next release. 
![cell](https://user-images.githubusercontent.com/11336532/99831637-497cd900-2b57-11eb-9a9f-248eed5c04c5.png)

**Comment by ShikOfTheRa** [comment]
OK - I'll close as done ready for next release
