### ISSUE TITLE
flight one falcox support

### ISSUE THREAD

**Issue by ludxio** [ShikOfTheRa/scarab-osd#626]
Can I use mwosd with falcox and how? On flight one support they told me that I can use osd emulator on PC to configure my revolt v3 boards(I have 5 of them), or to use dji fpv googles which works through msp. As far as I know mwosd works with msp, too. I would like to be able to change pids and presets in the osd menu on analog. I have tried to flash micro minim with 1.9.2.0 variant flightone_MSP, but I have only this:
![130155120_224657139039156_3011841742324341853_n](https://user-images.githubusercontent.com/75564040/101276871-4bc67080-37b0-11eb-86fd-260c2a149a3c.jpg)
 both on old flight one 1.2.94 and the newest falcox on the board. I have set msp to serial 3.

**Comment by ShikOfTheRa** [comment]
You need to upload mwosd fonts...

I have never used flight one so not going to be able to help much - Also not sure what MSP pid support there is from the FC
