### ISSUE TITLE
FC passthrough not working with Kiss

### ISSUE THREAD

**Issue by AngusCox** [ShikOfTheRa/scarab-osd#627]
Talking with Alexander Fedorov, one of Kiss developers, there could be a way to use Kiss FC as passthrough. The GPS configuration inside Kiss could be use to read and write the OSD. Setting the correct com speed I was able to receive 0 (ceros) from the OSD, but on the other hand I wasn't able to connect the GUI to the OSD using the passthrough feature.
Is there any possibility to check this issue and make it work for Kiss users? Not having to solder and resolder again each time we want to make an OSD change will be great.
Thanks

**Comment by ShikOfTheRa** [comment]
Hi - if we send you new GUI would you be able to test?

**Comment by AngusCox** [comment]
> Hi - if we send you new GUI would you be able to test?

Sure, I can test it without a problem.

**Comment by ShikOfTheRa** [comment]
Not able to create a MAC version at present. Would you be able to test a PC version in any way?

**Comment by AngusCox** [comment]
> Not able to create a MAC version at present. Would you be able to test a PC version in any way?

Yes, I can use a VM to install Windows and the GUI. But on the other hand I only have the licensed version for Mac. So I will not be able to test the write option with the PC version.

**Comment by ShikOfTheRa** [comment]
Hi - can you send an email top "spam@flypix.co.uk" - will reply with gui and kiss  v2 file to test.

**Comment by AngusCox** [comment]
> Hi - can you send an email top "[spam@flypix.co.uk](mailto:spam@flypix.co.uk)" - will reply with gui and kiss v2 file to test.

Done!

**Comment by xaviergriffon** [comment]
Hi (Happy New Year),
This is a very interesting development, if you need another beta tester, don't hesitate to ask me.

**Comment by AngusCox** [comment]
Using new Kiss v2.0.0.0 hex and same configurator version on OSX works perfectly.
<img width="1252" alt="OSX MWOSD GUI" src="https://user-images.githubusercontent.com/54340236/103486953-56d8e480-4de0-11eb-9a4a-c5e28a89b734.png">

Using same hex version but on Windows, I don't have the option to select Kiss from the connection options so it is not working for now.
![Windows MWOSD GUI](https://user-images.githubusercontent.com/54340236/103487032-044bf800-4de1-11eb-8fd2-a0ed07eff76a.jpg)

**Comment by ShikOfTheRa** [comment]
OK - it is good news with OSX! It is great work by GUI dev error414....

for Windows - my error, I uploaded wrong win version... updated and here if required
https://drive.google.com/drive/folders/1nB-tWqwoN-zKOJ7YhumGC0QTusEWCV6I

**Comment by xaviergriffon** [comment]
I've tested all OS.
With KISS v2, it works great!
With KISS v1, it doesn't work. In the logs, we have the message "Set passthrought Fail" but the FC seems to be in "passthrought" mode because it is no longer possible to connect it to KISS GUI.

In the GUI, it would be good to put a message to remind the user to set the OSD as GPS under KISS GUI.

**Comment by ShikOfTheRa** [comment]
Thanks Xavier. Yes only expect it to work with V2

Maybe a link to this?
https://github.com/ShikOfTheRa/scarab-osd/wiki/Passthrough

**Comment by xaviergriffon** [comment]
Absolutely agree, the wiki is perfect !
