### ISSUE TITLE
PX4 VTOL Support?

### ISSUE THREAD

**Issue by jeremyyano** [ShikOfTheRa/scarab-osd#634]
Is VTOL support implemented for PX4? I'm getting no data in MWOSD 1.9.2.0 PX4 fixed wing mode. I also tried the APM quadplane mode, no data there either. 

My autopilot is a Holybro Durandal running PX4 1.11.3, generic quadplane VTOL. Params are set, MAV_1 outputting OSD on TELEM2, minimOSD verified working on standard fixed wing PX4 aircraft.

Any help is much appreciated.

**Comment by skol101** [comment]
How did you fix it @jeremyyano ?
