### ISSUE TITLE
Mavlink Alt support

### ISSUE THREAD

**Issue by RMFPV** [ShikOfTheRa/scarab-osd#635]
Please make Alt to be displayed from Mavlink, instead of calculating in OSD. Ardupilot sends relative Alt, as far as I know.
It will give better idea of values that autopilot operates.

**Comment by ShikOfTheRa** [comment]
OK - I will have a look. I am finally able to restart on MWOSD.

Alt is typically calculated by noting alt when disarmed, then subtracting that in any future
So in theory, it should always be same if relative altitude is sent

**Comment by ShikOfTheRa** [comment]
OK to close?
