### ISSUE TITLE
Activate AHRS using IMU on I2C port

### ISSUE THREAD

**Issue by modifaer** [ShikOfTheRa/scarab-osd#636]
Idea is to activate artificial horizon by using a GY-85 IMU at the I2C port of the Aeromax OSD instead of the data feed from a FC. What steps need to be done to implement such a feature? I am new to Arduino coding at all and interested to learn.
Target application is fixed wing FPV.

**Comment by ShikOfTheRa** [comment]
Probably start with something like this:
https://arduino.stackexchange.com/questions/58190/how-to-read-the-raw-data-from-gy-85-module
Prepare it working outside of MWOSD to replace variables used in pitch /roll 

Variable to change in MWOSD: MwAngle[i] where i=0-2 for roll/pitch yaw (but can't remember order)
