### ISSUE TITLE
KISS FC WITH BLHELI32 ESC

### ISSUE THREAD

**Issue by hulandy** [ShikOfTheRa/scarab-osd#642]
Struggling with this issue for a long time. That is I can't use a blheli32 esc with mwosd for current measurement. For kiss users like me, the reason of using mwosd is mainly because we don't use kiss escs. with kiss escs everything is simple. 
The problem is almost all blheli32 escs don't have a fully functional telemetry, because they are using "on board ADC current sensor" measurement. For betaflight there is a pin just for current sensor in to use.   But kiss only support telemetry method. That is why mwosd is the choice. How ever, I can make direct voltage measurement works but not current. I'm using 6s batteries witch is majority nowadays. The current numbers on the osd just stay static no matter how I push the throttle.  
Please help me, to tell me how to set up the osd in order to use the direct voltage and current working at the same time. Thanks in advance!

**Comment by ShikOfTheRa** [comment]
Hi - steps are in calibration guide.

Main things are:

1. Amperage – direct connect - select this for Amperage values from sensor connected directly to OSD.
2. Analog sensor type – 1.1v is more accurate, but mandatory to use 5v for > 4s or if using direct analog RSSI or current sensors

https://github.com/ShikOfTheRa/scarab-osd/wiki/Calibration
