### ISSUE TITLE
large battery capacity

### ISSUE THREAD

**Issue by umeloman** [ShikOfTheRa/scarab-osd#643]
Hello! Recently I've got new issue, I think it's in OSD. On large drone battery capacity became to negative digit after 32750mAh (then it goes to -32750mAh and start going to 0). Looks like it is some max point of memory or some. Maybe it is better to change mAh to Ah for example  after 10000mAh and then show it like 10.21Ah, 32,76Ah or so? MicroMinimOSD + Ardupilot. Thank you!

**Comment by umeloman** [comment]
Thanks for quick reply! Yes, I was first with question about 12S LiPo battery voltage and now capacity is around 64Ah. It will be fine with 1 digit after point, no problem. I'm glad it is possible at least and you are healthy and online! Thank you, good luck!

**Comment by ShikOfTheRa** [comment]
BTW - can you share a bit of info about your aircraft? 12s / 64AH sounds very interesting!!

**Comment by umeloman** [comment]
It is BD625 25KG (MTOW up to 50kg) Agricultural drone based on Hobbywing X9
propulsion system with 34" props
https://ae01.alicdn.com/kf/H8915c91ab39749afadfa7cfc40dbb5b4c.jpg

вт, 7 вер. 2021 о 11:02 ShikOfTheRa ***@***.***> пише:

**Comment by ShikOfTheRa** [comment]
OMG. It is huge. 
I have large tricopter that is 1m between motors and 15 inch props and is the biggest have ever seen

**Comment by umeloman** [comment]
Hello! I hope you are fine! This question is still actual for me. Thank you!

**Comment by ShikOfTheRa** [comment]
Hi - sorry for delay - it is not forgotten - I have just been busy with day job and finishing off another development project.

MAybe 4 weeks I will be free to complete

**Comment by umeloman** [comment]
Hi! How are you? This thing is still actual for me. Now I'm using ver 2.0 pre release, also added GPS Alt and Baro Alt and both are not correct when GPS signal is lost

**Comment by ShikOfTheRa** [comment]
Hello, is this still required. Today I found my development unit after 1 year in storage so will be completing a few requests
If yes, does the amp draw display correctly? And what is the maximum amp draw approx of your drone

**Comment by ShikOfTheRa** [comment]
Hi - this is done. 
It is not available in pre-compiled binaries that can flash from GUI until next release. If this is an issue, or not sure how to build your own using arduino, please re-open.

https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide

**Comment by umeloman** [comment]
Thank you! Now it is mismatch with the simbols mAh to Ah. I can draw Ah instead of mAh, but up to 9999mAh there is no  "m" letter, like meters in distance ot altitude values. Itneresting challenge for me =)

**Comment by ShikOfTheRa** [comment]
Hi - here is a temporary solution. It is not available in pre-compiled binaries that can flash from GUI so it will require:

1 Custom installation ( flash using arduino )
https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide

2 Load fonts (Edit, load font from file, and select file from fonts folder in zip file below)


https://github.com/ShikOfTheRa/scarab-osd/archive/refs/heads/Battery-display-AH.zip

I am not planning any more updates for MWOSD. It is near end of life with very little capacity and also the number of users have reduced as they migrate to newer platforms. MWOSD will probably remain static now for many years.
