### ISSUE TITLE
minimOSD Vario with MS5611 GY63

### ISSUE THREAD

**Issue by tobif00** [ShikOfTheRa/scarab-osd#646]
Hi I'm using a minimOSD with KV Mod without a FC. Is there a possibility to use a MS5611baro for KKAUDIOVARIO via the ISP  (SPI) Interface?

Thank a lot.

**Comment by ShikOfTheRa** [comment]
Yes - see following. It can be enabled in config.h I don't think anyone ever used it so hope it still works!!

/********************       KK Audio Vario / climbrate Settings         ************************/
A highly accurate / sensitive Audio Vario from KapeteinKuk
Uses MS5611 pressure sensor connected by I2C and simple circuit added to OSD
Only supported by VIRTUALPILOT AEROMAX hardware unless able to carry out very fine soldering. Refer to links below
Wiki:  https://github.com/ShikOfTheRa/scarab-osd/wiki/Audio-Vario
Hardware: https://github.com/ShikOfTheRa/scarab-osd/blob/master/OTHER/DOCUMENTATION/VIRTUALPILOT%20AEROMAX/VP%20AEROMAX%20with%20I2C%20BARO%20VARIO.jpg

//#define KKAUDIOVARIO AUDIOPIN     // Enable this for audio vario. AUDIOPIN = D2 on AEROMAX hardware. Alternatively use A3 (RSSI) with other hardware
//#define AUDIOVARIOSWITCH          // Enable this to use screen layouts to enable/disable vario. If visual vario is displayed, the audio vario is on
#define KKDEADBANDLOW  -25          // Deadband threshold for sinking (Set to -500 to disable sink tones). 0 for no deadband
#define KKDEADBANDHIGH  15          // Deadband threshold for climbing. 0 for no deadband 



Also early video of GPS only vario.
