### ISSUE TITLE
Requesting Addition of Additional Unit Support

### ISSUE THREAD

**Issue by dtmasetti** [ShikOfTheRa/scarab-osd#649]
Hello! As an aspiring aircraft pilot, I work with a lot of folks that tend to work in units of knots. I also have some folks that like to use m/s. 

It would be very useful to have the ability to modify the airspeed units beyond just mph and km/hr. Is this something we could add?

Thanks!
Dan

**Comment by ShikOfTheRa** [comment]
Hi Dan - this is possible, but there is very little memory left. 
Is it only airspeed units required? I assume distance, altitude is OK.
