### ISSUE TITLE
Minimosd micro fails to store a new font

### ISSUE THREAD

**Issue by frog32** [ShikOfTheRa/scarab-osd#65]
I tried multiple times to load the provided font and never got any error message. The font it is displaying on the video signal is still the font that came preloaded with the osd.
Tried lowering the baudrate for programming and an older version. Nothing worked so far. Any idea?

**Comment by ShikOfTheRa** [comment]
yes - check the faq - one of the points covers the usual issues. lack of voltage from usb programmer or output stage of osd on the minim style boards
