### ISSUE TITLE
Baudrate change to 115200?

### ISSUE THREAD

**Issue by DangerD1024** [ShikOfTheRa/scarab-osd#654]
I don't have free serial, but i have telemetry running on 115200 so i want to parallel TX wire (like in the past).
But how i can change 57600 to 115200 in MWOSD?

**Comment by ShikOfTheRa** [comment]
Sorry for late reply.

Assuming this is ardu?

Basically you have to create a custom build / hex file to upload. Link is below.

in config.h, need to correct baud rate, OSD hardware, Flight controller and aircraft type.
https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide


Note once changed to 115k, the gui will have to be changed to that if you want to configure

**Comment by ShikOfTheRa** [comment]
ah - pretty much the same as far as teh OSD is concerned. Just a few subltle differences
