### ISSUE TITLE
Crazy idea: MAVlink support?

### ISSUE THREAD

**Issue by cmavr8** [ShikOfTheRa/scarab-osd#7]
Seeing how active, properly setup and developed this project is, I can't help but wonder why the equivalent project for ardupilot is so underdeveloped.

Taking into account that the whole ardupilot community has to rely on the MinimOSD-extra project, it's painful to watch how slowly that moves, how badly organized it is and how behind it has fallen. I don't mean to criticize the developers, they're doing their best and we all only have so much time left after our day jobs, but the truth is that that project needs changes. I'm just saying that MW OSD's progress is impressive.

So, I was thinking, how hard would it be for MW OSD to support parsing of the MAVlink protocol, so that it can be used on APM/Pixhawk setups, too? I guess this is the relevant code https://github.com/diydrones/MinimOSD-Extra/blob/master/MinimOsd-Extra/MAVLink.ino

This is not a feature request, just a discussion.

**Comment by hayden-t** [comment]
I think it would be pretty easy and something our main developer shikra has mentioned to me too: > " today its called mwosd - mw being multiwii, but maybe we have to consider changing this in future - now supports baseflight etc + standalone gps. I would like to put ardupilot in there too."

**Comment by OshCFII** [comment]
I run both a Pixhawk (ardupilot) as well as Cleanflight.   It would be great to run the same OSD on both platforms.

**Comment by ShikOfTheRa** [comment]
Yes - I would like to do this. Possibly 1.5
It just needs some time to find out the info. 

If someone else has time to do that would be even better:)

**Comment by ShikOfTheRa** [comment]
Guys I am going to close this - its on the future roadmap so no need to duplicate
