### ISSUE TITLE
Current values from FC off by an order of magnitude

### ISSUE THREAD

**Issue by dustin** [ShikOfTheRa/scarab-osd#71]
I upgraded from 1.3 and had current display from FC working fine.  I seem to get the right values now if I enable "legacy MSP" support for current sensing, but that throws the baseflight GUI off by an order of magnitude the other way.

This is somewhat workable, but it'd be nice if baseflight and MWOSD agreed.

**Comment by ShikOfTheRa** [comment]
Good catch. I missed that. Bit of a rush as was just about to release 1.4 and noticed the baseflight change...
Its hard to keep on top of the MSP changes across all platforms!

Have amended baseflight_pr on repo to include this.

Adding this line into config.h will solve if you prefer..
 #define AMPERAGECORRECT
