### ISSUE TITLE
can't set roll rate

### ISSUE THREAD

**Issue by dustin** [ShikOfTheRa/scarab-osd#85]
I'm running baseflight_pr and tried to adjust roll and pitch rate in the field.  Pitch rate took, but roll rate reset itself after change.

**Comment by ShikOfTheRa** [comment]
OK - will take a look. Unable to test this at moment.

**Comment by fly4props** [comment]
Hi ShikOfTheRa, I to am trying to set my yaw rate , roll/pitch rate via osd and it is just resetting back to what I have set it in the FC gui . Running CleanFlight 1.9 SPracingF3 . And thanks for all the hard work you put into this project!

**Comment by dustin** [comment]
@fly4props, this sounds unrelated.  Different FC firmware, different
feature.

**Comment by fly4props** [comment]
@dusten ahh I had mwosd 1.3 working so I could adjust pids. I thought this wold also work. no such luck, Ill just go back to the 1.3. Thanks

**Comment by ShikOfTheRa** [comment]
@dustin - BF_PR now removed. I had a look at the code and they no longer change P+R using the same serial MSP. So only versions up to up to and including Stable 2015.05.13 are supported. Versions / release after that will not be supported. Sorry...

**Comment by ShikOfTheRa** [comment]
@dustin 
Actually looking at the code, it appears 2015.03.27 is last full supported release. After that Pitch + Roll rates not supported... 

@fly4props latest repo should be working now

**Comment by dustin** [comment]
Does this mean only separate roll and pitch rates are supported moving forward?

**Comment by ShikOfTheRa** [comment]
At the moment it means unable to modify pitch and roll for releases after 2015.03.27
They have removed the ability to set teh P+R within the normal serial MSP where this is done.

I saw changes and added in the P+R code, but the baseflight guys subsequently removed it and put it in their own config serial MSP code. Its a pain in the ass for me, but understand why they did it. Its a different approach to Cleanflight. I am working on a solution

**Comment by ShikOfTheRa** [comment]
Beta 4 here contains hopefully a solution for latest Baseflight release with separate RC pitch/roll rates.
I have tested tonight with a copter on the bench and it seems to work - reads the settings OK, made changes, wrote back and verified OK.

Test very carefully - there is always potential for bad results when saving - hold copter down to be sure! or disable props
https://github.com/ShikOfTheRa/scarab-osd/releases

**Comment by ShikOfTheRa** [comment]
OK - had some confirmations its resolve din latest. I am using and have tested myself so pretty confident its OK
