### ISSUE TITLE
Can't update fonts in 1.4

### ISSUE THREAD

**Issue by olelille** [ShikOfTheRa/scarab-osd#89]
Hi,
I can't update the fonts on 1.4 and above on my micro OSD. Version 1.3 is working OK

**Comment by ShikOfTheRa** [comment]
Hello, 
There is an issue I think with 1.4 which affected font updates. Available in 1.4.2 beta 2 from here: 
https://github.com/ShikOfTheRa/scarab-osd/releases

I have same OSD and this morning changed fonts many times with no isses
