### ISSUE TITLE
RC rates not saving under cleanflight .63.

### ISSUE THREAD

**Issue by rgury** [ShikOfTheRa/scarab-osd#9]

**Comment by VirtualEnder** [comment]
The serial protocol was updated in cleanflight 1.8.X to separate out roll and pitch rates.  Nothing is saving at all on an of the rates in MWOSD now as a result of the change.

**Comment by ShikOfTheRa** [comment]
Yes - this is next item on my list! Will be looking to implement an interim solution for this in next couple of days. At least until Supersopp or me have time to implement a more elegant solution.

**Comment by ShikOfTheRa** [comment]
Interim solution in here for test
https://github.com/ShikOfTheRa/scarab-osd/blob/master/DOCUMENTATION/Downloads.md

**Comment by Arakon** [comment]
Using R1.4 Pre 1.1, saving of  RC rates still doesn't work. PIDs work just fine, however.

**Comment by ShikOfTheRa** [comment]
Hello - are you able to test R1.4 Pre 1.2 for me?. Sorry for hassle but I don't have a working config of cleanflight at the moment. If this doesn't work I'll convert my copter to test.

Download in here:
https://github.com/ShikOfTheRa/scarab-osd/blob/master/DOCUMENTATION/Downloads.md
Only really need to update the OSD sketch, but there are also a few GUI changes / improvements as per the feedback I read this morning.

**Comment by ShikOfTheRa** [comment]
Thanks mate - typo there well spotted!! Hate keep having to ask someone to test. Sooner I get a working cf install again the better.

The original issue was I didnt realise CF checked to ensure there was 10 bytes in MSP. Didn't know that. I guess BF does the same too. 

Updated the repo and zip build for testers. Hopefully before anyone realised!

**Comment by Arakon** [comment]
Working now, just gave it a try.

**Comment by ShikOfTheRa** [comment]
brill - will leave open for a bit just in case anything else needed

**Comment by ShikOfTheRa** [comment]
Now updated and with better stuff from supersopp
