### ISSUE TITLE
OSD not displaying

### ISSUE THREAD

**Issue by xNuno** [ShikOfTheRa/scarab-osd#90]
Hi, trying for the first time MWOSD but for some reason after compile, upload and configure...the screen don't show nothing...just the image from cam. Tried Rush-OSD and it works perfectly...

While on tests I'm not connecting the OSD to the CC3D with CleanFlight...

Any Tips?

**Comment by ShikOfTheRa** [comment]
Have you reviewed the FAQ -? Try changing the pal/NTSC setting/ Fixes 99% of issues. Don't believe camera label either !

**Comment by xNuno** [comment]
It's solved...installed lastest PRE firmware...now for some reason CC3D freezes with CleanFlight...need to troubleshoot...

**Comment by ShikOfTheRa** [comment]
Thanks for feedback
