### ISSUE TITLE
Config GUI freezes after reading configuration (Baud19200) 1.4.2B5

### ISSUE THREAD

**Issue by Gregmaan** [ShikOfTheRa/scarab-osd#93]
When I wan´t to configure 1.4.2b5 the GUI freezes after reading configuration.

I tested it with 19200 baud and MSP speed low and medium.

Then I configured it with the 1.4.1 gui and it seems to work.

**Comment by ShikOfTheRa** [comment]
mmm I haven't been able to replicate this. 
Could you try wiping the eeprom using the default blank sketch with arduino IDE.
It may be there is some value in there that the GUI not like?

**Comment by ShikOfTheRa** [comment]
Hello. Please can you try the latest release?
Both GUI and OSD together

**Comment by ShikOfTheRa** [comment]
Have you been able to try teh latest release to confirm?

**Comment by Gregmaan** [comment]
Sorry for the late reply. This iisue is fixed with 1.5.0
Cheers
Gregor
