### ISSUE TITLE
unable to change pid setting

### ISSUE THREAD

**Issue by lichtl** [ShikOfTheRa/scarab-osd#98]
With latest version 1.4.2.8 I'm unable to change PID's on a cleanflight 1.9.0

When changing the PID they straight jump back to the previous setting (once stick is centered)

https://www.dropbox.com/s/bxerq0ajerskwov/Config.h?dl=0 (config.h)

Below a short video
https://www.dropbox.com/s/bkde1n1hgh7t499/223243.AVI?dl=0

**Comment by ShikOfTheRa** [comment]
Yes - apologies my error.
Resolved subject to test on a live board. tested in simulator as far as possible.
https://github.com/ShikOfTheRa/scarab-osd/releases/tag/v1.4.2.9

**Comment by lichtl** [comment]
ok thanks. will test it later today.

**Comment by lichtl** [comment]
Tested 1.4.10 working
